CANoScope: gui/bit_analysis_view.c File Reference
bit_analysis_view.c File Reference
GTK Bit Analysis tab for reverse-engineering classic CAN payloads.
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/bit_analysis.h"
Data Structures
struct ba_survey_row_t
struct bit_ui_t
struct analysis_work_t
Macros
#define BA_SURVEY_MAX_IDS 256
#define BA_UNIQUE_TRACK 64
#define BA_UI_REFRESH_MS 100
#define BA_UI_ANALYZE_MAX_SAMPLES 5000u
Enumerations
enum {
SURV_COL_LABEL = 0 , SURV_COL_ID , SURV_COL_EXT , SURV_COL_DIR ,
SURV_COL_FD , SURV_COL_DLC , SURV_COL_COUNT , SURV_COL_MEAN ,
SURV_COL_JITTER , SURV_COL_CHANGED , SURV_COL_CHANGE_RATE , SURV_COL_UNIQUE ,
SURV_COL_DATA , SURV_COL_NUM
}
enum {
SEG_COL_NUM = 0 , SEG_COL_TYPE , SEG_COL_LABEL , SEG_COL_VALUE ,
SEG_COL_FRAMES , SEG_COL_NUM_COLS
}
enum {
CAND_COL_RANK = 0 , CAND_COL_START , CAND_COL_DBC_START , CAND_COL_LEN ,
CAND_COL_ORDER , CAND_COL_SIGNED , CAND_COL_PEARSON , CAND_COL_SPEARMAN ,
CAND_COL_R2 , CAND_COL_FACTOR , CAND_COL_OFFSET , CAND_COL_MAE ,
CAND_COL_VAL_N , CAND_COL_VAL_MAE , CAND_COL_LAG , CAND_COL_TRANSITIONS ,
CAND_COL_COUNTER , CAND_COL_TIMESTAMP , CAND_COL_TS_RES , CAND_COL_CHECKSUM ,
CAND_COL_MUX , CAND_COL_MUX_VALUES , CAND_COL_MUX_FRAMES , CAND_COL_MUX_BITS ,
CAND_COL_MUX_RANGES , CAND_COL_SCORE , CAND_COL_CONF , CAND_COL_INDEX ,
CAND_COL_NUM
}
enum ba_view_mode_t {
BA_VIEW_LIVE = 0 , BA_VIEW_BASELINE , BA_VIEW_XOR , BA_VIEW_ACTIVITY ,
BA_VIEW_ENTROPY , BA_VIEW_CORRELATION
}
Functions
static void refresh_target_store (void)
static void refresh_segment_store (void)
static void refresh_candidate_store (void)
static void refresh_summary (void)
static void refresh_field_preview (void)
static void refresh_bit_stats_label (void)
static void refresh_inspector (const ba_candidate_t *c)
static void sync_controls_from_session (void)
static void add_analysis_filter (GtkFileChooser *chooser)
static gboolean save_session_with_dialog (void)
static void on_target_changed (GtkComboBox *combo, gpointer data)
static void invalidate_analysis_results (void)
static void set_status (const char *fmt,...)
static uint64_t payload_hash (const uint8_t *data, uint8_t dlc)
static int bit_count64 (uint64_t v)
static ba_survey_row_t * find_survey_row (uint32_t id, uint8_t ext, uint8_t dir)
static void update_survey (const can_msg_t *msg)
static gboolean refresh_timer_cb (gpointer data)
static void ensure_refresh_timer (void)
static void format_target_label (char *buf, size_t sz, uint32_t id, uint8_t ext, uint8_t dir, uint8_t is_fd, uint8_t dlc, uint64_t count)
static gboolean get_selected_target (uint32_t *id, int *ext, uint8_t *dlc, guint *dir)
static ba_input_type_t active_input_type (void)
static ba_segment_type_t active_segment_type (void)
static ba_byte_order_t active_field_order (void)
static void sync_input_to_session (void)
static gboolean session_has_work (void)
static gboolean confirm_target_switch (uint32_t id, int ext, uint8_t dlc)
static void apply_controls_to_session (void)
static void on_start_clicked (GtkWidget *button, gpointer data)
static void on_pause_clicked (GtkWidget *button, gpointer data)
static void on_reset_clicked (GtkWidget *button, gpointer data)
static void on_baseline_clicked (GtkWidget *button, gpointer data)
static void on_add_marker_clicked (GtkWidget *button, gpointer data)
static void on_end_marker_clicked (GtkWidget *button, gpointer data)
static gboolean analysis_done_idle (gpointer data)
static gpointer analysis_thread_main (gpointer data)
static void on_analyze_clicked (GtkWidget *button, gpointer data)
static void on_candidate_selection_changed (GtkTreeSelection *selection, gpointer data)
static double cell_score_for_bit (uint16_t bit)
static gboolean on_matrix_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
static gboolean on_matrix_button (GtkWidget *widget, GdkEventButton *event, gpointer data)
static gboolean on_timeline_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
static void on_field_changed (GtkWidget *widget, gpointer data)
static void refresh_loaded_session_view (void)
static void on_save_session_clicked (GtkWidget *button, gpointer data)
static void on_load_session_clicked (GtkWidget *button, gpointer data)
static void on_mark_validated_clicked (GtkWidget *button, gpointer data)
static void on_promote_clicked (GtkWidget *button, gpointer data)
void gui_bit_analysis_reset (void)
Reset the current Bit Analysis session.
void gui_bit_analysis_trace_changed (void)
Notify Bit Analysis that trace contents changed.
void gui_bit_analysis_handle_message (const can_msg_t *msg)
Feed one CAN frame to the Bit Analysis tab.
static GtkWidget * make_tree (GtkListStore *store)
static void add_text_column (GtkWidget *view, const char *title, int model_col, int min_width)
GtkWidget * gui_create_bit_analysis_view (void)
Build the Bit Analysis tab for CAN reverse engineering.
Variables
static bit_ui_t s_ba
Detailed Description
GTK Bit Analysis tab for reverse-engineering classic CAN payloads.
Definition in file bit_analysis_view.c.
Macro Definition Documentation
BA_SURVEY_MAX_IDS
#define BA_SURVEY_MAX_IDS 256
Definition at line 17 of file bit_analysis_view.c.
BA_UNIQUE_TRACK
#define BA_UNIQUE_TRACK 64
Definition at line 18 of file bit_analysis_view.c.
BA_UI_REFRESH_MS
#define BA_UI_REFRESH_MS 100
Definition at line 19 of file bit_analysis_view.c.
BA_UI_ANALYZE_MAX_SAMPLES
#define BA_UI_ANALYZE_MAX_SAMPLES 5000u
Definition at line 20 of file bit_analysis_view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SURV_COL_LABEL
SURV_COL_ID
SURV_COL_EXT
SURV_COL_DIR
SURV_COL_FD
SURV_COL_DLC
SURV_COL_COUNT
SURV_COL_MEAN
SURV_COL_JITTER
SURV_COL_CHANGED
SURV_COL_CHANGE_RATE
SURV_COL_UNIQUE
SURV_COL_DATA
SURV_COL_NUM
Definition at line 45 of file bit_analysis_view.c.
anonymous enum
anonymous enum
Enumerator
SEG_COL_NUM
SEG_COL_TYPE
SEG_COL_LABEL
SEG_COL_VALUE
SEG_COL_FRAMES
SEG_COL_NUM_COLS
Definition at line 62 of file bit_analysis_view.c.
anonymous enum
anonymous enum
Enumerator
CAND_COL_RANK
CAND_COL_START
CAND_COL_DBC_START
CAND_COL_LEN
CAND_COL_ORDER
CAND_COL_SIGNED
CAND_COL_PEARSON
CAND_COL_SPEARMAN
CAND_COL_R2
CAND_COL_FACTOR
CAND_COL_OFFSET
CAND_COL_MAE
CAND_COL_VAL_N
CAND_COL_VAL_MAE
CAND_COL_LAG
CAND_COL_TRANSITIONS
CAND_COL_COUNTER
CAND_COL_TIMESTAMP
CAND_COL_TS_RES
CAND_COL_CHECKSUM
CAND_COL_MUX
CAND_COL_MUX_VALUES
CAND_COL_MUX_FRAMES
CAND_COL_MUX_BITS
CAND_COL_MUX_RANGES
CAND_COL_SCORE
CAND_COL_CONF
CAND_COL_INDEX
CAND_COL_NUM
Definition at line 71 of file bit_analysis_view.c.
ba_view_mode_t
enum ba_view_mode_t
Enumerator
BA_VIEW_LIVE
BA_VIEW_BASELINE
BA_VIEW_XOR
BA_VIEW_ACTIVITY
BA_VIEW_ENTROPY
BA_VIEW_CORRELATION
Definition at line 103 of file bit_analysis_view.c.
Function Documentation
refresh_target_store()
static void refresh_target_store (void) static
< Frame direction: received.
Definition at line 341 of file bit_analysis_view.c.
References bit_count64(), CAN_DIR_RX, format_target_label(), gui_format_data(), GUI_TRACE_DATA_TEXT_MAX, label, n, on_target_changed(), s_ba, bit_ui_t::suppress_target_changed, SURV_COL_CHANGE_RATE, SURV_COL_CHANGED, SURV_COL_COUNT, SURV_COL_DATA, SURV_COL_DIR, SURV_COL_DLC, SURV_COL_EXT, SURV_COL_FD, SURV_COL_ID, SURV_COL_JITTER, SURV_COL_LABEL, SURV_COL_MEAN, SURV_COL_UNIQUE, bit_ui_t::survey, bit_ui_t::survey_count, bit_ui_t::target_combo, and bit_ui_t::target_store.
Referenced by refresh_timer_cb().
refresh_segment_store()
static void refresh_segment_store (void) static
Definition at line 883 of file bit_analysis_view.c.
References ba_segment_type_name(), n, s_ba, SEG_COL_FRAMES, SEG_COL_LABEL, SEG_COL_NUM, SEG_COL_TYPE, SEG_COL_VALUE, ba_session_t::segment_count, bit_ui_t::segment_store, ba_session_t::segments, bit_ui_t::session, and value.
Referenced by on_add_marker_clicked(), on_end_marker_clicked(), on_reset_clicked(), on_target_changed(), refresh_loaded_session_view(), and refresh_timer_cb().
refresh_candidate_store()
static void refresh_candidate_store (void) static
Definition at line 907 of file bit_analysis_view.c.
References ba_byte_order_name(), BA_NOTE_MAX, CAND_COL_CHECKSUM, CAND_COL_CONF, CAND_COL_COUNTER, CAND_COL_DBC_START, CAND_COL_FACTOR, CAND_COL_INDEX, CAND_COL_LAG, CAND_COL_LEN, CAND_COL_MAE, CAND_COL_MUX, CAND_COL_MUX_BITS, CAND_COL_MUX_FRAMES, CAND_COL_MUX_RANGES, CAND_COL_MUX_VALUES, CAND_COL_OFFSET, CAND_COL_ORDER, CAND_COL_PEARSON, CAND_COL_R2, CAND_COL_RANK, CAND_COL_SCORE, CAND_COL_SIGNED, CAND_COL_SPEARMAN, CAND_COL_START, CAND_COL_TIMESTAMP, CAND_COL_TRANSITIONS, CAND_COL_TS_RES, CAND_COL_VAL_MAE, CAND_COL_VAL_N, ba_session_t::candidate_count, bit_ui_t::candidate_store, ba_session_t::candidates, n, s_ba, and bit_ui_t::session.
Referenced by analysis_done_idle(), on_mark_validated_clicked(), on_reset_clicked(), on_target_changed(), and refresh_loaded_session_view().
refresh_summary()
static void refresh_summary (void) static
Definition at line 861 of file bit_analysis_view.c.
References ba_session_state_name(), ba_session_t::baseline_valid, ba_session_t::can_id, ba_session_t::candidate_count, ba_session_t::dropped_samples, ba_session_t::expected_dlc, ba_session_t::is_extended, n, s_ba, ba_session_t::sample_capacity, ba_session_t::sample_count, bit_ui_t::session, ba_session_t::state, bit_ui_t::state_label, and bit_ui_t::summary_label.
Referenced by analysis_done_idle(), gui_create_bit_analysis_view(), on_analyze_clicked(), on_reset_clicked(), on_target_changed(), refresh_loaded_session_view(), and refresh_timer_cb().
refresh_field_preview()
static void refresh_field_preview (void) static
Definition at line 1077 of file bit_analysis_view.c.
References active_field_order(), ba_extract_unsigned(), ba_sign_extend(), ba_session_t::candidate_count, ba_session_t::candidates, ba_session_t::expected_dlc, bit_ui_t::field_len_spin, bit_ui_t::field_phys_label, bit_ui_t::field_raw_label, bit_ui_t::field_signed_check, bit_ui_t::field_start_spin, ba_session_t::latest_data, ba_session_t::latest_dlc, n, ba_candidate_t::offset, s_ba, bit_ui_t::selected_candidate, and bit_ui_t::session.
Referenced by analysis_done_idle(), on_candidate_selection_changed(), on_field_changed(), on_matrix_button(), on_target_changed(), refresh_loaded_session_view(), and refresh_timer_cb().
refresh_bit_stats_label()
static void refresh_bit_stats_label (void) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 1110 of file bit_analysis_view.c.
References ba_session_t::analyze_fd_payload, BA_CLASSIC_MAX_BITS, BA_CLASSIC_MAX_BYTES, BA_FD_MAX_BITS, ba_get_bit(), ba_session_t::baseline_bits, ba_session_t::baseline_valid, ba_session_t::bit_stats, bit_ui_t::bit_stats_label, ba_session_t::expected_dlc, bit_ui_t::field_start_spin, ba_session_t::latest_data, ba_session_t::latest_dlc, n, s_ba, bit_ui_t::selected_bit, and bit_ui_t::session.
Referenced by analysis_done_idle(), gui_create_bit_analysis_view(), on_candidate_selection_changed(), on_field_changed(), on_matrix_button(), on_reset_clicked(), on_target_changed(), refresh_loaded_session_view(), and refresh_timer_cb().
refresh_inspector()
static void refresh_inspector (const ba_candidate_t * c) static
Definition at line 987 of file bit_analysis_view.c.
References ba_byte_order_name(), bit_ui_t::inspector_label, n, and s_ba.
Referenced by on_candidate_selection_changed(), on_mark_validated_clicked(), on_target_changed(), and refresh_loaded_session_view().
sync_controls_from_session()
static void sync_controls_from_session (void) static
Definition at line 579 of file bit_analysis_view.c.
References bit_ui_t::accept_varying_check, ba_session_t::accept_varying_dlc, ba_session_t::analyze_fd_payload, ba_session_t::can_id, ba_session_t::current_input_value, bit_ui_t::dir_combo, bit_ui_t::dlc_spin, ba_session_t::expected_dlc, bit_ui_t::fd_full_check, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, bit_ui_t::input_name_entry, ba_session_t::input_type, bit_ui_t::input_type_combo, ba_session_t::input_unit, bit_ui_t::input_unit_entry, bit_ui_t::input_value_spin, ba_session_t::is_extended, n, s_ba, bit_ui_t::session, bit_ui_t::suppress_target_changed, SURV_COL_DLC, SURV_COL_EXT, SURV_COL_ID, bit_ui_t::target_combo, and bit_ui_t::target_store.
Referenced by confirm_target_switch(), and refresh_loaded_session_view().
add_analysis_filter()
static void add_analysis_filter (GtkFileChooser * chooser) static
Definition at line 1438 of file bit_analysis_view.c.
References n.
Referenced by on_load_session_clicked(), and save_session_with_dialog().
save_session_with_dialog()
static gboolean save_session_with_dialog (void) static
Definition at line 1468 of file bit_analysis_view.c.
References add_analysis_filter(), ba_session_save_json(), g_gui, n, s_ba, bit_ui_t::session, set_status(), and gui_widgets_t::window.
Referenced by confirm_target_switch(), and on_save_session_clicked().
on_target_changed()
static void on_target_changed (GtkComboBox * combo, gpointer data) static
< Frame direction: received.
< Frame direction: received.
< Frame direction: transmitted.
Definition at line 524 of file bit_analysis_view.c.
References BA_CLASSIC_MAX_BYTES, ba_session_configure_target(), CAN_DIR_RX, CAN_DIR_TX, confirm_target_switch(), bit_ui_t::dlc_spin, get_selected_target(), ba_session_t::include_rx, ba_session_t::include_tx, invalidate_analysis_results(), bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_candidate_store(), refresh_field_preview(), refresh_inspector(), refresh_segment_store(), refresh_summary(), s_ba, bit_ui_t::selected_bit, bit_ui_t::selected_candidate, bit_ui_t::session, set_status(), bit_ui_t::suppress_target_changed, and bit_ui_t::timeline_area.
Referenced by gui_create_bit_analysis_view(), and refresh_target_store().
invalidate_analysis_results()
static void invalidate_analysis_results (void) static
Definition at line 174 of file bit_analysis_view.c.
References bit_ui_t::analysis_generation, and s_ba.
Referenced by on_load_session_clicked(), on_reset_clicked(), and on_target_changed().
set_status()
static void set_status (const char * fmt, ...) static
Definition at line 179 of file bit_analysis_view.c.
References n, s_ba, and bit_ui_t::status_label.
Referenced by analysis_done_idle(), confirm_target_switch(), on_add_marker_clicked(), on_analyze_clicked(), on_baseline_clicked(), on_end_marker_clicked(), on_load_session_clicked(), on_mark_validated_clicked(), on_pause_clicked(), on_promote_clicked(), on_reset_clicked(), on_start_clicked(), on_target_changed(), and save_session_with_dialog().
payload_hash()
static uint64_t payload_hash (const uint8_t * data, uint8_t dlc) static
Definition at line 191 of file bit_analysis_view.c.
References n.
Referenced by update_survey().
bit_count64()
static int bit_count64 (uint64_t v) static
Definition at line 203 of file bit_analysis_view.c.
References n.
Referenced by refresh_target_store().
find_survey_row()
static ba_survey_row_t * find_survey_row (uint32_t id, uint8_t ext, uint8_t dir) static
Definition at line 213 of file bit_analysis_view.c.
References BA_SURVEY_MAX_IDS, n, s_ba, bit_ui_t::survey, and bit_ui_t::survey_count.
Referenced by update_survey().
update_survey()
static void update_survey (const can_msg_t * msg) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 233 of file bit_analysis_view.c.
References BA_CLASSIC_MAX_BYTES, ba_timespec_to_ns(), BA_UNIQUE_TRACK, CANFD_DATA_MAX, bit_ui_t::dirty_survey, find_survey_row(), n, payload_hash(), and s_ba.
Referenced by gui_bit_analysis_handle_message().
refresh_timer_cb()
static gboolean refresh_timer_cb (gpointer data) static
Definition at line 299 of file bit_analysis_view.c.
References bit_ui_t::dirty_survey, bit_ui_t::dirty_view, bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_field_preview(), refresh_segment_store(), refresh_summary(), refresh_target_store(), s_ba, and bit_ui_t::timeline_area.
Referenced by ensure_refresh_timer().
ensure_refresh_timer()
static void ensure_refresh_timer (void) static
Definition at line 320 of file bit_analysis_view.c.
References BA_UI_REFRESH_MS, n, bit_ui_t::refresh_source, refresh_timer_cb(), and s_ba.
Referenced by gui_create_bit_analysis_view().
format_target_label()
static void format_target_label (char * buf, size_t sz, uint32_t id, uint8_t ext, uint8_t dir, uint8_t is_fd, uint8_t dlc, uint64_t count) static
< Frame direction: transmitted.
Definition at line 327 of file bit_analysis_view.c.
References CAN_DIR_TX, count, gui_format_id(), GUI_TRACE_ID_TEXT_MAX, and n.
Referenced by refresh_target_store().
get_selected_target()
static gboolean get_selected_target (uint32_t * id, int * ext, uint8_t * dlc, guint * dir) static
< Frame direction: received.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 413 of file bit_analysis_view.c.
References CAN_DIR_RX, CANFD_DATA_MAX, n, s_ba, SURV_COL_DIR, SURV_COL_DLC, SURV_COL_EXT, SURV_COL_ID, bit_ui_t::target_combo, and bit_ui_t::target_store.
Referenced by on_target_changed().
active_input_type()
static ba_input_type_t active_input_type (void) static
Definition at line 437 of file bit_analysis_view.c.
References BA_INPUT_CONTINUOUS, BA_INPUT_EVENT_ONLY, bit_ui_t::input_type_combo, n, and s_ba.
Referenced by sync_input_to_session().
active_segment_type()
static ba_segment_type_t active_segment_type (void) static
Definition at line 445 of file bit_analysis_view.c.
References BA_SEGMENT_EVENT, BA_SEGMENT_STEP, n, s_ba, and bit_ui_t::segment_type_combo.
Referenced by on_add_marker_clicked().
active_field_order()
static ba_byte_order_t active_field_order (void) static
Definition at line 453 of file bit_analysis_view.c.
References BA_BYTE_ORDER_INTEL, BA_BYTE_ORDER_MOTOROLA, bit_ui_t::field_order_combo, n, and s_ba.
Referenced by on_timeline_draw(), and refresh_field_preview().
sync_input_to_session()
static void sync_input_to_session (void) static
Definition at line 459 of file bit_analysis_view.c.
References active_input_type(), BA_INPUT_EVENT_ONLY, ba_session_set_input(), bit_ui_t::input_name_entry, bit_ui_t::input_unit_entry, bit_ui_t::input_value_spin, n, s_ba, bit_ui_t::session, and value.
Referenced by apply_controls_to_session(), and on_add_marker_clicked().
session_has_work()
static gboolean session_has_work (void) static
Definition at line 469 of file bit_analysis_view.c.
References BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, ba_session_t::baseline_valid, ba_session_t::candidate_count, s_ba, ba_session_t::sample_count, ba_session_t::segment_count, bit_ui_t::session, and ba_session_t::state.
Referenced by confirm_target_switch().
confirm_target_switch()
static gboolean confirm_target_switch (uint32_t id, int ext, uint8_t dlc) static
Definition at line 479 of file bit_analysis_view.c.
References BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, BA_SESSION_PAUSED, ba_session_t::can_id, ba_session_t::expected_dlc, g_gui, ba_session_t::is_extended, n, s_ba, save_session_with_dialog(), bit_ui_t::session, session_has_work(), set_status(), ba_session_t::state, sync_controls_from_session(), and gui_widgets_t::window.
Referenced by on_target_changed().
apply_controls_to_session()
static void apply_controls_to_session (void) static
Definition at line 562 of file bit_analysis_view.c.
References bit_ui_t::accept_varying_check, ba_session_t::accept_varying_dlc, ba_session_t::analyze_fd_payload, ba_session_configure_target(), ba_session_t::can_id, bit_ui_t::dir_combo, bit_ui_t::dlc_spin, bit_ui_t::fd_full_check, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::is_extended, n, s_ba, bit_ui_t::session, and sync_input_to_session().
Referenced by on_start_clicked().
on_start_clicked()
static void on_start_clicked (GtkWidget * button, gpointer data) static
Definition at line 641 of file bit_analysis_view.c.
References apply_controls_to_session(), BA_SESSION_CAPTURING, bit_ui_t::dirty_view, n, s_ba, bit_ui_t::session, set_status(), and ba_session_t::state.
Referenced by gui_create_bit_analysis_view().
on_pause_clicked()
static void on_pause_clicked (GtkWidget * button, gpointer data) static
Definition at line 651 of file bit_analysis_view.c.
References BA_SESSION_CAPTURING, BA_SESSION_PAUSED, bit_ui_t::dirty_view, n, s_ba, bit_ui_t::session, set_status(), and ba_session_t::state.
Referenced by gui_create_bit_analysis_view().
on_reset_clicked()
static void on_reset_clicked (GtkWidget * button, gpointer data) static
Definition at line 665 of file bit_analysis_view.c.
References ba_session_configure_target(), ba_session_t::can_id, ba_session_t::expected_dlc, invalidate_analysis_results(), ba_session_t::is_extended, bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_candidate_store(), refresh_segment_store(), refresh_summary(), s_ba, bit_ui_t::selected_bit, bit_ui_t::selected_candidate, bit_ui_t::session, set_status(), and bit_ui_t::timeline_area.
Referenced by gui_bit_analysis_reset(), and gui_create_bit_analysis_view().
on_baseline_clicked()
static void on_baseline_clicked (GtkWidget * button, gpointer data) static
Definition at line 687 of file bit_analysis_view.c.
References ba_session_capture_baseline(), ba_session_t::baseline_sample_count, ba_session_t::baseline_valid, bit_ui_t::dirty_view, n, s_ba, ba_session_t::sample_count, bit_ui_t::session, and set_status().
Referenced by gui_create_bit_analysis_view().
on_add_marker_clicked()
static void on_add_marker_clicked (GtkWidget * button, gpointer data) static
Definition at line 702 of file bit_analysis_view.c.
References active_segment_type(), ba_segment_type_name(), ba_session_add_segment(), ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::input_unit, label, n, refresh_segment_store(), s_ba, bit_ui_t::segment_label_entry, bit_ui_t::session, set_status(), and sync_input_to_session().
Referenced by gui_create_bit_analysis_view().
on_end_marker_clicked()
static void on_end_marker_clicked (GtkWidget * button, gpointer data) static
Definition at line 721 of file bit_analysis_view.c.
References ba_session_end_segment(), n, refresh_segment_store(), s_ba, bit_ui_t::session, and set_status().
Referenced by gui_create_bit_analysis_view().
analysis_done_idle()
static gboolean analysis_done_idle (gpointer data) static
Definition at line 735 of file bit_analysis_view.c.
References bit_ui_t::analysis_generation, bit_ui_t::analysis_running, ba_session_destroy(), BA_SESSION_REVIEW, ba_session_t::bit_stats, ba_session_t::candidate_count, ba_session_t::candidates, bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_candidate_store(), refresh_field_preview(), refresh_summary(), s_ba, bit_ui_t::session, set_status(), ba_session_t::state, and bit_ui_t::timeline_area.
Referenced by analysis_thread_main().
analysis_thread_main()
static gpointer analysis_thread_main (gpointer data) static
Definition at line 765 of file bit_analysis_view.c.
References analysis_done_idle(), ba_session_analyze(), and n.
Referenced by on_analyze_clicked().
on_analyze_clicked()
static void on_analyze_clicked (GtkWidget * button, gpointer data) static
Definition at line 773 of file bit_analysis_view.c.
References ba_session_t::accept_varying_dlc, ba_session_t::active_segment, bit_ui_t::analysis_generation, bit_ui_t::analysis_running, analysis_thread_main(), ba_session_t::analyze_fd_payload, BA_LABEL_MAX, BA_SESSION_ANALYZING, ba_session_configure_target(), ba_session_init(), BA_UI_ANALYZE_MAX_SAMPLES, BA_UNIT_MAX, ba_session_t::baseline_bits, ba_session_t::baseline_data, ba_session_t::baseline_sample_count, ba_session_t::baseline_valid, ba_session_t::can_id, ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::dropped_samples, ba_session_t::expected_dlc, ba_session_t::first_ts_ns, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, ba_session_t::is_extended, ba_session_t::latest_data, ba_session_t::latest_dlc, ba_session_t::latest_ts_ns, n, ba_session_t::next_segment_id, refresh_summary(), s_ba, ba_session_t::sample_capacity, ba_session_t::sample_count, ba_session_t::sample_head, ba_session_t::samples, ba_session_t::segment_count, ba_session_t::segments, bit_ui_t::session, set_status(), ba_session_t::state, and ba_session_t::total_target_frames.
Referenced by gui_create_bit_analysis_view().
on_candidate_selection_changed()
static void on_candidate_selection_changed (GtkTreeSelection * selection, gpointer data) static
Definition at line 1043 of file bit_analysis_view.c.
References BA_BYTE_ORDER_MOTOROLA, CAND_COL_INDEX, ba_session_t::candidate_count, ba_session_t::candidates, bit_ui_t::field_len_spin, bit_ui_t::field_order_combo, bit_ui_t::field_signed_check, bit_ui_t::field_start_spin, bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_field_preview(), refresh_inspector(), s_ba, bit_ui_t::selected_candidate, bit_ui_t::session, and bit_ui_t::timeline_area.
Referenced by gui_create_bit_analysis_view().
cell_score_for_bit()
static double cell_score_for_bit (uint16_t bit) static
< Maximum payload of a CAN FD frame.
Definition at line 1161 of file bit_analysis_view.c.
References BA_FD_MAX_BITS, ba_get_bit(), BA_VIEW_ACTIVITY, BA_VIEW_BASELINE, BA_VIEW_CORRELATION, BA_VIEW_ENTROPY, BA_VIEW_LIVE, BA_VIEW_XOR, ba_session_t::baseline_bits, ba_session_t::baseline_valid, ba_session_t::bit_stats, ba_session_t::latest_data, bit_ui_t::mode_combo, n, s_ba, and bit_ui_t::session.
Referenced by on_matrix_draw().
on_matrix_draw()
static gboolean on_matrix_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Definition at line 1189 of file bit_analysis_view.c.
References ba_get_bit(), BA_VIEW_BASELINE, BA_VIEW_CORRELATION, BA_VIEW_LIVE, BA_VIEW_XOR, ba_session_t::baseline_bits, ba_session_t::baseline_valid, cell_score_for_bit(), bit_ui_t::field_len_spin, bit_ui_t::field_start_spin, label, ba_session_t::latest_data, bit_ui_t::mode_combo, n, s_ba, bit_ui_t::selected_bit, and bit_ui_t::session.
Referenced by gui_create_bit_analysis_view().
on_matrix_button()
static gboolean on_matrix_button (GtkWidget * widget, GdkEventButton * event, gpointer data) static
Definition at line 1287 of file bit_analysis_view.c.
References bit_ui_t::field_start_spin, n, refresh_bit_stats_label(), refresh_field_preview(), s_ba, bit_ui_t::selected_bit, and bit_ui_t::timeline_area.
Referenced by gui_create_bit_analysis_view().
on_timeline_draw()
static gboolean on_timeline_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Definition at line 1313 of file bit_analysis_view.c.
References active_field_order(), ba_extract_unsigned(), ba_sign_extend(), bit_ui_t::field_len_spin, bit_ui_t::field_signed_check, bit_ui_t::field_start_spin, ba_session_t::first_ts_ns, label, n, s_ba, ba_session_t::sample_capacity, ba_session_t::sample_count, ba_session_t::sample_head, ba_session_t::samples, bit_ui_t::session, and ba_sample_t::timestamp_ns.
Referenced by gui_create_bit_analysis_view().
on_field_changed()
static void on_field_changed (GtkWidget * widget, gpointer data) static
Definition at line 1426 of file bit_analysis_view.c.
References bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_field_preview(), s_ba, and bit_ui_t::timeline_area.
Referenced by gui_create_bit_analysis_view().
refresh_loaded_session_view()
static void refresh_loaded_session_view (void) static
Definition at line 1451 of file bit_analysis_view.c.
References bit_ui_t::matrix_area, n, refresh_bit_stats_label(), refresh_candidate_store(), refresh_field_preview(), refresh_inspector(), refresh_segment_store(), refresh_summary(), s_ba, bit_ui_t::selected_bit, bit_ui_t::selected_candidate, sync_controls_from_session(), and bit_ui_t::timeline_area.
Referenced by on_load_session_clicked().
on_save_session_clicked()
static void on_save_session_clicked (GtkWidget * button, gpointer data) static
Definition at line 1505 of file bit_analysis_view.c.
References n, and save_session_with_dialog().
Referenced by gui_create_bit_analysis_view().
on_load_session_clicked()
static void on_load_session_clicked (GtkWidget * button, gpointer data) static
Definition at line 1512 of file bit_analysis_view.c.
References add_analysis_filter(), ba_session_load_json(), g_gui, invalidate_analysis_results(), n, refresh_loaded_session_view(), s_ba, bit_ui_t::session, set_status(), and gui_widgets_t::window.
Referenced by gui_create_bit_analysis_view().
on_mark_validated_clicked()
static void on_mark_validated_clicked (GtkWidget * button, gpointer data) static
Definition at line 1540 of file bit_analysis_view.c.
References ba_candidate_validate_segments(), ba_session_t::candidate_count, ba_session_t::candidates, n, refresh_candidate_store(), refresh_inspector(), s_ba, bit_ui_t::selected_candidate, bit_ui_t::session, and set_status().
Referenced by gui_create_bit_analysis_view().
on_promote_clicked()
static void on_promote_clicked (GtkWidget * button, gpointer data) static
< Max stored message/signal comment.
Definition at line 1581 of file bit_analysis_view.c.
References BA_BYTE_ORDER_INTEL, ba_session_t::can_id, ba_session_t::candidate_count, ba_session_t::candidates, DBC_COMMENT_MAX, ba_session_t::expected_dlc, gui_db_creation_prefill_signal(), ba_session_t::input_unit, ba_session_t::is_extended, n, s_ba, bit_ui_t::selected_candidate, bit_ui_t::session, and set_status().
Referenced by gui_create_bit_analysis_view().
gui_bit_analysis_reset()
void gui_bit_analysis_reset (void)
Reset the current Bit Analysis session.
Definition at line 1622 of file bit_analysis_view.c.
References n, and on_reset_clicked().
gui_bit_analysis_trace_changed()
void gui_bit_analysis_trace_changed (void)
Notify Bit Analysis that trace contents changed.
Definition at line 1627 of file bit_analysis_view.c.
References bit_ui_t::dirty_survey, n, and s_ba.
gui_bit_analysis_handle_message()
void gui_bit_analysis_handle_message (const can_msg_t * msg)
Feed one CAN frame to the Bit Analysis tab.
Parameters
msg Frame; ignored when it does not match the active target.
Definition at line 1632 of file bit_analysis_view.c.
References ba_session_t::active_segment, ba_session_push_frame(), bit_ui_t::dirty_view, n, s_ba, ba_segment_t::sample_count, ba_session_t::segment_count, ba_session_t::segments, bit_ui_t::session, and update_survey().
Referenced by gui_add_message().
make_tree()
static GtkWidget * make_tree (GtkListStore * store) static
Definition at line 1648 of file bit_analysis_view.c.
References n.
Referenced by gui_create_bit_analysis_view().
add_text_column()
static void add_text_column (GtkWidget * view, const char * title, int model_col, int min_width) static
Definition at line 1657 of file bit_analysis_view.c.
References n.
Referenced by gui_create_bit_analysis_view().
gui_create_bit_analysis_view()
GtkWidget * gui_create_bit_analysis_view (void)
Build the Bit Analysis tab for CAN reverse engineering.
Returns
A container widget for use as a notebook page.
Definition at line 1668 of file bit_analysis_view.c.
References bit_ui_t::accept_varying_check, add_text_column(), BA_DEFAULT_CAPACITY, BA_INPUT_CONTINUOUS, BA_SEGMENT_EVENT, BA_SEGMENT_STEP, ba_segment_type_name(), ba_session_init(), BA_UNIT_MAX, BA_VIEW_LIVE, bit_ui_t::bit_stats_label, CAND_COL_CHECKSUM, CAND_COL_CONF, CAND_COL_COUNTER, CAND_COL_DBC_START, CAND_COL_FACTOR, CAND_COL_LAG, CAND_COL_LEN, CAND_COL_MAE, CAND_COL_MUX, CAND_COL_MUX_BITS, CAND_COL_MUX_FRAMES, CAND_COL_MUX_RANGES, CAND_COL_MUX_VALUES, CAND_COL_NUM, CAND_COL_OFFSET, CAND_COL_ORDER, CAND_COL_PEARSON, CAND_COL_R2, CAND_COL_RANK, CAND_COL_SCORE, CAND_COL_SIGNED, CAND_COL_SPEARMAN, CAND_COL_START, CAND_COL_TIMESTAMP, CAND_COL_TRANSITIONS, CAND_COL_TS_RES, CAND_COL_VAL_MAE, CAND_COL_VAL_N, bit_ui_t::candidate_store, bit_ui_t::candidate_view, bit_ui_t::dir_combo, bit_ui_t::dlc_spin, ensure_refresh_timer(), bit_ui_t::fd_full_check, bit_ui_t::field_len_spin, bit_ui_t::field_order_combo, bit_ui_t::field_phys_label, bit_ui_t::field_raw_label, bit_ui_t::field_signed_check, bit_ui_t::field_start_spin, bit_ui_t::input_name_entry, bit_ui_t::input_type_combo, bit_ui_t::input_unit_entry, bit_ui_t::input_value_spin, bit_ui_t::inspector_label, make_tree(), bit_ui_t::matrix_area, bit_ui_t::mode_combo, n, on_add_marker_clicked(), on_analyze_clicked(), on_baseline_clicked(), on_candidate_selection_changed(), on_end_marker_clicked(), on_field_changed(), on_load_session_clicked(), on_mark_validated_clicked(), on_matrix_button(), on_matrix_draw(), on_pause_clicked(), on_promote_clicked(), on_reset_clicked(), on_save_session_clicked(), on_start_clicked(), on_target_changed(), on_timeline_draw(), refresh_bit_stats_label(), refresh_summary(), s_ba, ba_session_t::samples, SEG_COL_FRAMES, SEG_COL_LABEL, SEG_COL_NUM, SEG_COL_NUM_COLS, SEG_COL_TYPE, SEG_COL_VALUE, bit_ui_t::segment_label_entry, bit_ui_t::segment_store, bit_ui_t::segment_type_combo, bit_ui_t::segment_view, bit_ui_t::selected_bit, bit_ui_t::selected_candidate, bit_ui_t::session, sig, bit_ui_t::status_label, bit_ui_t::summary_label, SURV_COL_CHANGE_RATE, SURV_COL_CHANGED, SURV_COL_JITTER, SURV_COL_LABEL, SURV_COL_MEAN, SURV_COL_NUM, SURV_COL_UNIQUE, bit_ui_t::target_combo, bit_ui_t::target_store, and bit_ui_t::timeline_area.
Referenced by gui_create_main_window().
Variable Documentation
s_ba
bit_ui_t s_ba static
Definition at line 160 of file bit_analysis_view.c.
Referenced by active_field_order(), active_input_type(), active_segment_type(), analysis_done_idle(), apply_controls_to_session(), cell_score_for_bit(), confirm_target_switch(), ensure_refresh_timer(), find_survey_row(), get_selected_target(), gui_bit_analysis_handle_message(), gui_bit_analysis_trace_changed(), gui_create_bit_analysis_view(), invalidate_analysis_results(), on_add_marker_clicked(), on_analyze_clicked(), on_baseline_clicked(), on_candidate_selection_changed(), on_end_marker_clicked(), on_field_changed(), on_load_session_clicked(), on_mark_validated_clicked(), on_matrix_button(), on_matrix_draw(), on_pause_clicked(), on_promote_clicked(), on_reset_clicked(), on_start_clicked(), on_target_changed(), on_timeline_draw(), refresh_bit_stats_label(), refresh_candidate_store(), refresh_field_preview(), refresh_inspector(), refresh_loaded_session_view(), refresh_segment_store(), refresh_summary(), refresh_target_store(), refresh_timer_cb(), save_session_with_dialog(), session_has_work(), set_status(), sync_controls_from_session(), sync_input_to_session(), and update_survey().