CANoScope: analysis/bit_analysis.c File Reference
bit_analysis.c File Reference
GTK-independent CAN payload bit analysis engine.
#include "../inc/bit_analysis.h"
#include <ctype.h>
#include <errno.h>
#include <inttypes.h>
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct rank_item_t
Macros
#define BA_ANALYZE_MAX_SAMPLES 5000u
#define BA_INVALID_BIT 0xFFFFu
#define BA_TRANSITION_WINDOW_NS 250000000LL
Functions
static int sample_index (const ba_session_t *s, size_t logical)
static int cmp_candidate_desc (const void *a, const void *b)
static int cmp_double (const void *a, const void *b)
static int cmp_rank_item (const void *a, const void *b)
static void safe_copy (char *dst, size_t dstsz, const char *src)
int64_t ba_timespec_to_ns (const struct timespec *ts)
Convert a POSIX timespec to nanoseconds.
uint8_t ba_get_bit (const uint8_t *data, uint16_t bit)
Return one canonical LSB0 bit from a payload buffer.
int ba_field_fits (uint16_t start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Return non-zero when a field fits inside the selected bit range.
uint16_t ba_dbc_to_canonical_start_bit (uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a DBC start bit to the canonical absolute start bit.
uint16_t ba_canonical_to_dbc_start_bit (uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a canonical start bit to the corresponding DBC start bit.
uint64_t ba_extract_unsigned_dbc (const uint8_t *data, uint8_t dlc, uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from DBC start-bit coordinates.
uint64_t ba_extract_unsigned (const uint8_t *data, uint8_t dlc, uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from canonical coordinates.
int64_t ba_sign_extend (uint64_t raw, uint8_t bit_length)
Sign-extend an unsigned raw value as two's-complement.
static double entropy_for_probability (double p)
static double pearson_corr (const double *x, const double *y, size_t n)
static void compute_ranks (const double *v, size_t n, double *rank)
static double spearman_corr (const double *x, const double *y, size_t n)
static uint32_t unique_count (double *v, size_t n)
static void regression_metrics (const double *raw, const double *input, size_t n, ba_candidate_t *c)
int ba_session_init (ba_session_t *s, size_t capacity)
Initialise a Bit Analysis session and allocate its sample ring.
void ba_session_destroy (ba_session_t *s)
Release memory owned by a Bit Analysis session.
void ba_session_reset (ba_session_t *s)
Reset samples, markers, baseline, and analysis results for a target.
void ba_session_configure_target (ba_session_t *s, uint32_t can_id, int is_extended, uint8_t expected_dlc)
Select the CAN identifier and DLC that the session should capture.
void ba_session_set_input (ba_session_t *s, ba_input_type_t type, const char *name, double value, const char *unit, int valid)
Set the current manual input value associated with subsequent frames.
uint32_t ba_session_add_segment (ba_session_t *s, ba_segment_type_t type, const char *label, double input_value, int input_valid, int64_t timestamp_ns)
Start a new experiment segment at a timestamp.
void ba_session_end_segment (ba_session_t *s, int64_t timestamp_ns)
Close the active experiment segment.
static int matches_target (const ba_session_t *s, const can_msg_t *msg)
int ba_session_push_frame (ba_session_t *s, const can_msg_t *msg)
Filter and append one CAN frame to the target-frame ring buffer.
static int session_has_baseline_segment (const ba_session_t *s)
static int sample_is_in_baseline_segment (const ba_session_t *s, const ba_sample_t *sample)
void ba_session_capture_baseline (ba_session_t *s)
Build a statistical baseline from baseline segments or all samples.
static size_t collect_analysis_samples (const ba_session_t *s, const ba_sample_t **out, size_t max_out)
static double compute_best_lag_ms (const ba_sample_t **samples, const double *raw, size_t n, double *scratch_raw, double *scratch_input, double *best_corr_out)
static void compute_bit_stats (ba_session_t *s, const ba_sample_t **samples, size_t n, uint16_t total_bits)
static double counter_score_for_values (const double *raw, size_t n, uint8_t bit_length)
static double estimate_lag_step_ns (const ba_sample_t **samples, size_t n)
static double lagged_corr_for_values (const ba_sample_t **samples, const double *raw, size_t n, int64_t lag_ns, double *scratch_raw, double *scratch_input)
static size_t collect_lagged_pairs (const ba_sample_t **samples, const double *raw, size_t n, int64_t lag_ns, double *out_raw, double *out_input)
static double checksum_like_score (const ba_candidate_t *c, const ba_session_t *s)
static double timestamp_score_for_values (ba_candidate_t *c, const ba_sample_t **samples, const double *raw, size_t n)
static int candidate_contains_bit (const ba_candidate_t *c, uint16_t bit)
static void append_bit_range (char *buf, size_t bufsz, uint16_t start, uint16_t end)
static double mux_score_for_values (ba_candidate_t *c, const ba_session_t *s, const ba_sample_t **samples, const double *raw, size_t n)
static double transition_score_for_values (const ba_sample_t **samples, const double *raw, size_t n, double best_lag_ms, uint32_t *match_count_out, uint32_t *transition_count_out)
static void fill_confidence (ba_candidate_t *c)
static double candidate_retention_score (const ba_candidate_t *c)
static void append_candidate (ba_session_t *s, const ba_candidate_t *src)
static void evaluate_candidate (ba_session_t *s, const ba_sample_t **samples, size_t n, uint16_t canonical_start, uint16_t dbc_start, uint8_t len, ba_byte_order_t order, int is_signed)
void ba_session_analyze (ba_session_t *s, uint8_t max_field_len)
Compute bit statistics and ranked field candidates.
static int sample_is_in_segment_type (const ba_session_t *s, const ba_sample_t *sample, ba_segment_type_t type)
static const ba_sample_t * lag_aligned_input_sample (const ba_session_t *s, size_t logical_sample, int64_t lag_ns, size_t *input_logical)
int ba_candidate_validate_segments (const ba_session_t *s, const ba_candidate_t *c, double max_mean_absolute_error, size_t *sample_count_out, double *mean_absolute_error_out, double *max_absolute_error_out)
Validate a candidate against independent validation segments.
static void set_err (char *err, size_t errsz, const char *fmt,...)
static void json_write_escaped (FILE *fp, const char *s)
static void json_write_hex (FILE *fp, const uint8_t *data, size_t len)
static const char * json_skip_ws (const char *p, const char *end)
static const char * json_skip_string (const char *p, const char *end)
static const char * json_find_key (const char *start, const char *end, const char *key)
static int json_get_range (const char *start, const char *end, const char *key, char open, char close, const char **out_start, const char **out_end)
static int json_next_object (const char **cursor, const char *end, const char **obj_start, const char **obj_end)
static int json_get_u64 (const char *start, const char *end, const char *key, uint64_t *out)
static int json_get_i64 (const char *start, const char *end, const char *key, int64_t *out)
static int json_get_double (const char *start, const char *end, const char *key, double *out)
static int json_get_bool (const char *start, const char *end, const char *key, uint8_t *out)
static int json_get_string (const char *start, const char *end, const char *key, char *out, size_t outsz)
static int hex_value (int ch)
static size_t parse_hex_bytes (const char *hex, uint8_t *out, size_t outsz)
static void parse_segment_object (const char *start, const char *end, ba_segment_t *seg)
static void parse_candidate_object (const char *start, const char *end, ba_candidate_t *c)
static int parse_sample_object (const char *start, const char *end, ba_sample_t *sample)
int ba_session_save_json (const ba_session_t *s, const char *path, char *err, size_t errsz)
Save a complete analysis session as JSON.
int ba_session_load_json (ba_session_t *s, const char *path, char *err, size_t errsz)
Load an analysis session from JSON.
const char * ba_byte_order_name (ba_byte_order_t order)
Human-readable byte-order label.
const char * ba_segment_type_name (ba_segment_type_t type)
Human-readable segment-type label.
const char * ba_input_type_name (ba_input_type_t type)
Human-readable input-type label.
const char * ba_session_state_name (ba_session_state_t state)
Human-readable session-state label.
Detailed Description
GTK-independent CAN payload bit analysis engine.
Definition in file bit_analysis.c.
Macro Definition Documentation
BA_ANALYZE_MAX_SAMPLES
#define BA_ANALYZE_MAX_SAMPLES 5000u
Definition at line 17 of file bit_analysis.c.
BA_INVALID_BIT
#define BA_INVALID_BIT 0xFFFFu
Definition at line 18 of file bit_analysis.c.
BA_TRANSITION_WINDOW_NS
#define BA_TRANSITION_WINDOW_NS 250000000LL
Definition at line 19 of file bit_analysis.c.
Function Documentation
sample_index()
static int sample_index (const ba_session_t * s, size_t logical) static
Definition at line 26 of file bit_analysis.c.
References ba_session_t::sample_capacity, ba_session_t::sample_count, and ba_session_t::sample_head.
Referenced by ba_candidate_validate_segments(), ba_session_capture_baseline(), ba_session_save_json(), collect_analysis_samples(), and lag_aligned_input_sample().
cmp_candidate_desc()
static int cmp_candidate_desc (const void * a, const void * b) static
Definition at line 32 of file bit_analysis.c.
References ba_candidate_t::total_score.
Referenced by ba_session_analyze().
cmp_double()
static int cmp_double (const void * a, const void * b) static
Definition at line 40 of file bit_analysis.c.
Referenced by unique_count().
cmp_rank_item()
static int cmp_rank_item (const void * a, const void * b) static
Definition at line 47 of file bit_analysis.c.
References rank_item_t::v.
Referenced by compute_ranks().
safe_copy()
static void safe_copy (char * dst, size_t dstsz, const char * src) static
Definition at line 54 of file bit_analysis.c.
Referenced by ba_session_add_segment(), ba_session_init(), ba_session_reset(), ba_session_set_input(), and fill_confidence().
ba_timespec_to_ns()
int64_t ba_timespec_to_ns (const struct timespec * ts)
Convert a POSIX timespec to nanoseconds.
Definition at line 61 of file bit_analysis.c.
Referenced by ba_session_push_frame(), and update_survey().
ba_get_bit()
uint8_t ba_get_bit (const uint8_t * data, uint16_t bit)
Return one canonical LSB0 bit from a payload buffer.
Definition at line 68 of file bit_analysis.c.
Referenced by ba_extract_unsigned_dbc(), ba_session_capture_baseline(), ba_session_load_json(), cell_score_for_bit(), compute_bit_stats(), mux_score_for_values(), on_matrix_draw(), and refresh_bit_stats_label().
ba_field_fits()
int ba_field_fits (uint16_t start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Return non-zero when a field fits inside the selected bit range.
Definition at line 73 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL.
Referenced by ba_canonical_to_dbc_start_bit(), ba_dbc_to_canonical_start_bit(), ba_extract_unsigned_dbc(), and ba_session_analyze().
ba_dbc_to_canonical_start_bit()
uint16_t ba_dbc_to_canonical_start_bit (uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a DBC start bit to the canonical absolute start bit.
Definition at line 95 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_field_fits(), and BA_INVALID_BIT.
Referenced by ba_canonical_to_dbc_start_bit(), ba_session_analyze(), and extraction_tests().
ba_canonical_to_dbc_start_bit()
uint16_t ba_canonical_to_dbc_start_bit (uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a canonical start bit to the corresponding DBC start bit.
Definition at line 118 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_dbc_to_canonical_start_bit(), ba_field_fits(), and BA_INVALID_BIT.
Referenced by ba_extract_unsigned(), and extraction_tests().
ba_extract_unsigned_dbc()
uint64_t ba_extract_unsigned_dbc (const uint8_t * data, uint8_t dlc, uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from DBC start-bit coordinates.
Definition at line 137 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_field_fits(), ba_get_bit(), and value.
Referenced by ba_candidate_validate_segments(), ba_extract_unsigned(), and evaluate_candidate().
ba_extract_unsigned()
uint64_t ba_extract_unsigned (const uint8_t * data, uint8_t dlc, uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from canonical coordinates.
Parameters
data Payload bytes.
dlc Payload length in bytes.
canonical_start_bit Byte0/bit0 absolute start coordinate.
bit_length Field length in bits.
order Intel or Motorola byte order.
Returns
Extracted raw value, or 0 when the field does not fit.
Definition at line 170 of file bit_analysis.c.
References ba_canonical_to_dbc_start_bit(), ba_extract_unsigned_dbc(), and BA_INVALID_BIT.
Referenced by candidate_tests(), extraction_tests(), on_timeline_draw(), and refresh_field_preview().
ba_sign_extend()
int64_t ba_sign_extend (uint64_t raw, uint8_t bit_length)
Sign-extend an unsigned raw value as two's-complement.
Definition at line 185 of file bit_analysis.c.
Referenced by ba_candidate_validate_segments(), evaluate_candidate(), extraction_tests(), on_timeline_draw(), refresh_field_preview(), and validate_candidate_dbc_roundtrip().
entropy_for_probability()
static double entropy_for_probability (double p) static
Definition at line 199 of file bit_analysis.c.
Referenced by compute_bit_stats().
pearson_corr()
static double pearson_corr (const double * x, const double * y, size_t n) static
Definition at line 206 of file bit_analysis.c.
References n.
Referenced by compute_bit_stats(), lagged_corr_for_values(), regression_metrics(), and spearman_corr().
compute_ranks()
static void compute_ranks (const double * v, size_t n, double * rank) static
Definition at line 232 of file bit_analysis.c.
References cmp_rank_item(), rank_item_t::idx, n, and rank_item_t::v.
Referenced by spearman_corr().
spearman_corr()
static double spearman_corr (const double * x, const double * y, size_t n) static
Definition at line 256 of file bit_analysis.c.
References compute_ranks(), n, and pearson_corr().
Referenced by regression_metrics().
unique_count()
static uint32_t unique_count (double * v, size_t n) static
Definition at line 275 of file bit_analysis.c.
References cmp_double(), count, and n.
Referenced by evaluate_candidate().
regression_metrics()
static void regression_metrics (const double * raw, const double * input, size_t n, ba_candidate_t * c) static
Definition at line 288 of file bit_analysis.c.
References ba_candidate_t::factor, ba_candidate_t::max_absolute_error, ba_candidate_t::mean_absolute_error, ba_candidate_t::monotonicity, n, ba_candidate_t::offset, ba_candidate_t::pearson, pearson_corr(), ba_candidate_t::r_squared, ba_candidate_t::spearman, and spearman_corr().
Referenced by evaluate_candidate().
ba_session_init()
int ba_session_init (ba_session_t * s, size_t capacity)
Initialise a Bit Analysis session and allocate its sample ring.
Parameters
s Session object to initialise.
capacity Ring capacity in target frames; 0 uses BA_DEFAULT_CAPACITY.
Returns
0 on success, -1 on allocation or argument failure.
Definition at line 339 of file bit_analysis.c.
References ba_session_t::active_segment, BA_CLASSIC_MAX_BYTES, BA_DEFAULT_CAPACITY, BA_INPUT_CONTINUOUS, BA_SESSION_IDLE, ba_session_t::expected_dlc, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, ba_session_t::next_segment_id, safe_copy(), ba_session_t::sample_capacity, ba_session_t::samples, and ba_session_t::state.
Referenced by ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), gui_create_bit_analysis_view(), lag_tests(), motorola_candidate_tests(), mux_tests(), on_analyze_clicked(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_destroy()
void ba_session_destroy (ba_session_t * s)
Release memory owned by a Bit Analysis session.
Parameters
s Session to destroy; may be NULL.
Definition at line 362 of file bit_analysis.c.
References ba_session_t::samples.
Referenced by analysis_done_idle(), ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_reset()
void ba_session_reset (ba_session_t * s)
Reset samples, markers, baseline, and analysis results for a target.
Parameters
s Session to reset while preserving allocated storage and settings.
Definition at line 370 of file bit_analysis.c.
References ba_session_t::accept_varying_dlc, ba_session_t::active_segment, ba_session_t::analyze_fd_payload, BA_LABEL_MAX, BA_SESSION_READY, BA_UNIT_MAX, ba_session_t::can_id, ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::expected_dlc, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, ba_session_t::is_extended, ba_session_t::next_segment_id, safe_copy(), ba_session_t::sample_capacity, samples, ba_session_t::samples, and ba_session_t::state.
Referenced by ba_session_configure_target().
ba_session_configure_target()
void ba_session_configure_target (ba_session_t * s, uint32_t can_id, int is_extended, uint8_t expected_dlc)
Select the CAN identifier and DLC that the session should capture.
Parameters
s Session to configure.
can_id Standard or extended CAN identifier.
is_extended Non-zero for a 29-bit identifier.
expected_dlc Expected payload length in bytes.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 409 of file bit_analysis.c.
References ba_session_reset(), ba_session_t::can_id, CANFD_DATA_MAX, ba_session_t::expected_dlc, and ba_session_t::is_extended.
Referenced by apply_controls_to_session(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), on_analyze_clicked(), on_reset_clicked(), on_target_changed(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_set_input()
void ba_session_set_input (ba_session_t * s, ba_input_type_t type, const char * name, double value, const char * unit, int valid)
Set the current manual input value associated with subsequent frames.
Parameters
s Active session.
type Input channel type.
name Human-readable input name.
value Numeric input value.
unit Engineering unit.
valid Non-zero when value is meaningful for fitting.
Definition at line 423 of file bit_analysis.c.
References ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, safe_copy(), and value.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), lag_tests(), motorola_candidate_tests(), signed_candidate_tests(), sync_input_to_session(), transition_match_tests(), and validation_segment_tests().
ba_session_add_segment()
uint32_t ba_session_add_segment (ba_session_t * s, ba_segment_type_t type, const char * label, double input_value, int input_valid, int64_t timestamp_ns)
Start a new experiment segment at a timestamp.
Parameters
s Active session.
type Segment type.
label Optional user-visible label.
input_value Input value assigned to the segment.
input_valid Non-zero if input_value should be used.
timestamp_ns Segment start timestamp in nanoseconds.
Returns
Non-zero segment id on success, 0 when no segment slot is available.
Definition at line 439 of file bit_analysis.c.
References ba_session_t::active_segment, BA_MAX_SEGMENTS, ba_session_end_segment(), ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_segment_t::first_sample, ba_segment_t::id, ba_segment_t::input_valid, ba_segment_t::input_value, label, ba_segment_t::label, ba_session_t::latest_ts_ns, ba_session_t::next_segment_id, safe_copy(), ba_session_t::segment_count, ba_session_t::segments, ba_segment_t::start_ns, ba_session_t::total_target_frames, and ba_segment_t::type.
Referenced by baseline_segment_tests(), candidate_tests(), on_add_marker_clicked(), and validation_segment_tests().
ba_session_end_segment()
void ba_session_end_segment (ba_session_t * s, int64_t timestamp_ns)
Close the active experiment segment.
Parameters
s Active session.
timestamp_ns End timestamp in nanoseconds; 0 uses latest sample time.
Definition at line 468 of file bit_analysis.c.
References ba_session_t::active_segment, ba_segment_t::end_ns, ba_segment_t::first_sample, ba_session_t::latest_ts_ns, ba_segment_t::sample_count, ba_session_t::segment_count, ba_session_t::segments, and ba_session_t::total_target_frames.
Referenced by ba_session_add_segment(), baseline_segment_tests(), candidate_tests(), on_end_marker_clicked(), and validation_segment_tests().
matches_target()
static int matches_target (const ba_session_t * s, const can_msg_t * msg) static
< Frame direction: received.
< Frame direction: transmitted.
Definition at line 480 of file bit_analysis.c.
References ba_session_t::accept_varying_dlc, ba_session_t::analyze_fd_payload, BA_CLASSIC_MAX_BYTES, CAN_DIR_RX, CAN_DIR_TX, ba_session_t::can_id, can_msg_t::direction, can_msg_t::dlc, ba_session_t::expected_dlc, can_msg_t::id, ba_session_t::include_rx, ba_session_t::include_tx, can_msg_t::is_error, ba_session_t::is_extended, can_msg_t::is_extended, and can_msg_t::is_remote.
Referenced by ba_session_push_frame().
ba_session_push_frame()
int ba_session_push_frame (ba_session_t * s, const can_msg_t * msg)
Filter and append one CAN frame to the target-frame ring buffer.
Parameters
s Active session.
msg CAN/CAN FD frame to evaluate.
Returns
1 when the frame was accepted and copied, otherwise 0.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 499 of file bit_analysis.c.
References ba_session_t::active_segment, BA_SESSION_CAPTURING, ba_timespec_to_ns(), CANFD_DATA_MAX, ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_sample_t::data, can_msg_t::data, ba_sample_t::direction, can_msg_t::direction, ba_sample_t::dlc, can_msg_t::dlc, ba_session_t::dropped_samples, ba_session_t::first_ts_ns, ba_segment_t::id, ba_sample_t::input_valid, ba_sample_t::input_value, ba_session_t::latest_data, ba_session_t::latest_dlc, ba_session_t::latest_ts_ns, matches_target(), ba_session_t::sample_capacity, ba_session_t::sample_count, ba_session_t::sample_head, ba_session_t::samples, ba_session_t::segment_count, ba_sample_t::segment_id, ba_session_t::segments, can_msg_t::seq, ba_sample_t::sequence, ba_session_t::state, can_msg_t::timestamp, ba_sample_t::timestamp_ns, and ba_session_t::total_target_frames.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), gui_bit_analysis_handle_message(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
session_has_baseline_segment()
static int session_has_baseline_segment (const ba_session_t * s) static
Definition at line 534 of file bit_analysis.c.
References BA_SEGMENT_BASELINE, ba_session_t::segment_count, ba_session_t::segments, and ba_segment_t::type.
Referenced by ba_session_capture_baseline().
sample_is_in_baseline_segment()
static int sample_is_in_baseline_segment (const ba_session_t * s, const ba_sample_t * sample) static
Definition at line 545 of file bit_analysis.c.
References BA_SEGMENT_BASELINE, ba_segment_t::id, ba_session_t::segment_count, ba_sample_t::segment_id, ba_session_t::segments, and ba_segment_t::type.
Referenced by ba_session_capture_baseline().
ba_session_capture_baseline()
void ba_session_capture_baseline (ba_session_t * s)
Build a statistical baseline from baseline segments or all samples.
Parameters
s Active session with target samples.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 558 of file bit_analysis.c.
References BA_FD_MAX_BITS, ba_get_bit(), ba_session_t::baseline_bits, ba_session_t::baseline_data, ba_session_t::baseline_sample_count, ba_session_t::baseline_valid, ba_sample_t::data, ba_session_t::expected_dlc, ba_session_t::latest_dlc, ba_session_t::sample_count, sample_index(), sample_is_in_baseline_segment(), ba_session_t::samples, and session_has_baseline_segment().
Referenced by baseline_segment_tests(), candidate_tests(), and on_baseline_clicked().
collect_analysis_samples()
static size_t collect_analysis_samples (const ba_session_t * s, const ba_sample_t ** out, size_t max_out) static
Definition at line 594 of file bit_analysis.c.
References n, ba_session_t::sample_count, sample_index(), and ba_session_t::samples.
Referenced by ba_session_analyze().
compute_best_lag_ms()
static double compute_best_lag_ms (const ba_sample_t ** samples, const double * raw, size_t n, double * scratch_raw, double * scratch_input, double * best_corr_out) static
Definition at line 810 of file bit_analysis.c.
References estimate_lag_step_ns(), lagged_corr_for_values(), n, and samples.
Referenced by compute_bit_stats(), and evaluate_candidate().
compute_bit_stats()
static void compute_bit_stats (ba_session_t * s, const ba_sample_t ** samples, size_t n, uint16_t total_bits) static
Definition at line 619 of file bit_analysis.c.
References BA_ANALYZE_MAX_SAMPLES, ba_get_bit(), ba_session_t::baseline_bits, ba_bit_stats_t::baseline_difference_rate, ba_session_t::baseline_valid, ba_bit_stats_t::baseline_value, ba_bit_stats_t::best_lag_ms, ba_session_t::bit_stats, compute_best_lag_ms(), ba_bit_stats_t::current_value, ba_bit_stats_t::entropy_bits, entropy_for_probability(), ba_bit_stats_t::flip_count, ba_bit_stats_t::flip_rate_hz, ba_bit_stats_t::is_constant, ba_bit_stats_t::lagged_score, n, ba_bit_stats_t::one_count, pearson_corr(), ba_bit_stats_t::pearson_correlation, ba_bit_stats_t::probability_one, ba_bit_stats_t::sample_count, samples, ba_bit_stats_t::state_separation, and ba_bit_stats_t::zero_count.
Referenced by ba_session_analyze().
counter_score_for_values()
static double counter_score_for_values (const double * raw, size_t n, uint8_t bit_length) static
Definition at line 718 of file bit_analysis.c.
References n.
Referenced by evaluate_candidate().
estimate_lag_step_ns()
static double estimate_lag_step_ns (const ba_sample_t ** samples, size_t n) static
Definition at line 737 of file bit_analysis.c.
References n, and samples.
Referenced by compute_best_lag_ms().
lagged_corr_for_values()
static double lagged_corr_for_values (const ba_sample_t ** samples, const double * raw, size_t n, int64_t lag_ns, double * scratch_raw, double * scratch_input) static
Definition at line 752 of file bit_analysis.c.
References n, pearson_corr(), and samples.
Referenced by compute_best_lag_ms().
collect_lagged_pairs()
static size_t collect_lagged_pairs (const ba_sample_t ** samples, const double * raw, size_t n, int64_t lag_ns, double * out_raw, double * out_input) static
Definition at line 781 of file bit_analysis.c.
References n, and samples.
Referenced by evaluate_candidate().
checksum_like_score()
static double checksum_like_score (const ba_candidate_t * c, const ba_session_t * s) static
Definition at line 845 of file bit_analysis.c.
References n.
Referenced by evaluate_candidate().
timestamp_score_for_values()
static double timestamp_score_for_values (ba_candidate_t * c, const ba_sample_t ** samples, const double * raw, size_t n) static
Definition at line 874 of file bit_analysis.c.
References n, and samples.
Referenced by evaluate_candidate().
candidate_contains_bit()
static int candidate_contains_bit (const ba_candidate_t * c, uint16_t bit) static
Definition at line 936 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, and n.
Referenced by mux_score_for_values().
append_bit_range()
static void append_bit_range (char * buf, size_t bufsz, uint16_t start, uint16_t end) static
Definition at line 956 of file bit_analysis.c.
References n.
Referenced by mux_score_for_values().
mux_score_for_values()
static double mux_score_for_values (ba_candidate_t * c, const ba_session_t * s, const ba_sample_t ** samples, const double * raw, size_t n) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 976 of file bit_analysis.c.
References append_bit_range(), BA_ANALYZE_MAX_SAMPLES, BA_CLASSIC_MAX_BYTES, BA_FD_MAX_BITS, BA_FD_MAX_BYTES, ba_get_bit(), candidate_contains_bit(), n, and samples.
Referenced by evaluate_candidate().
transition_score_for_values()
static double transition_score_for_values (const ba_sample_t ** samples, const double * raw, size_t n, double best_lag_ms, uint32_t * match_count_out, uint32_t * transition_count_out) static
Definition at line 1091 of file bit_analysis.c.
References BA_TRANSITION_WINDOW_NS, n, and samples.
Referenced by evaluate_candidate().
fill_confidence()
static void fill_confidence (ba_candidate_t * c) static
Definition at line 1190 of file bit_analysis.c.
References n, and safe_copy().
Referenced by evaluate_candidate().
candidate_retention_score()
static double candidate_retention_score (const ba_candidate_t * c) static
Definition at line 1209 of file bit_analysis.c.
References n.
Referenced by append_candidate().
append_candidate()
static void append_candidate (ba_session_t * s, const ba_candidate_t * src) static
Definition at line 1231 of file bit_analysis.c.
References BA_MAX_CANDIDATES, candidate_retention_score(), and n.
Referenced by evaluate_candidate().
evaluate_candidate()
static void evaluate_candidate (ba_session_t * s, const ba_sample_t ** samples, size_t n, uint16_t canonical_start, uint16_t dbc_start, uint8_t len, ba_byte_order_t order, int is_signed) static
< Maximum payload of a CAN FD frame.
Definition at line 1251 of file bit_analysis.c.
References append_candidate(), ba_extract_unsigned_dbc(), BA_FD_MAX_BITS, BA_INPUT_BOOLEAN, ba_sign_extend(), checksum_like_score(), collect_lagged_pairs(), compute_best_lag_ms(), counter_score_for_values(), fill_confidence(), mux_score_for_values(), n, regression_metrics(), samples, timestamp_score_for_values(), transition_score_for_values(), and unique_count().
Referenced by ba_session_analyze().
ba_session_analyze()
void ba_session_analyze (ba_session_t * s, uint8_t max_field_len)
Compute bit statistics and ranked field candidates.
Parameters
s Active session.
max_field_len Maximum contiguous field length to scan in bits.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 1455 of file bit_analysis.c.
References BA_ANALYZE_MAX_SAMPLES, BA_BYTE_ORDER_INTEL, BA_BYTE_ORDER_MOTOROLA, BA_CLASSIC_MAX_BYTES, ba_dbc_to_canonical_start_bit(), BA_FD_MAX_BYTES, ba_field_fits(), BA_INVALID_BIT, BA_SESSION_ANALYZING, BA_SESSION_REVIEW, cmp_candidate_desc(), collect_analysis_samples(), compute_bit_stats(), evaluate_candidate(), n, and samples.
Referenced by analysis_thread_main(), ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
sample_is_in_segment_type()
static int sample_is_in_segment_type (const ba_session_t * s, const ba_sample_t * sample, ba_segment_type_t type) static
Definition at line 1526 of file bit_analysis.c.
References n.
Referenced by ba_candidate_validate_segments().
lag_aligned_input_sample()
static const ba_sample_t * lag_aligned_input_sample (const ba_session_t * s, size_t logical_sample, int64_t lag_ns, size_t * input_logical) static
Definition at line 1540 of file bit_analysis.c.
References ba_sample_t::input_valid, n, and sample_index().
Referenced by ba_candidate_validate_segments().
ba_candidate_validate_segments()
int ba_candidate_validate_segments (const ba_session_t * s, const ba_candidate_t * c, double max_mean_absolute_error, size_t * sample_count_out, double * mean_absolute_error_out, double * max_absolute_error_out)
Validate a candidate against independent validation segments.
Parameters
s Session containing validation samples.
c Candidate to validate.
max_mean_absolute_error Negative for automatic tolerance.
sample_count_out Optional validated sample count output.
mean_absolute_error_out Optional validation MAE output.
max_absolute_error_out Optional validation max-error output.
Returns
1 when validation passes, otherwise 0.
Definition at line 1571 of file bit_analysis.c.
References ba_extract_unsigned_dbc(), BA_SEGMENT_VALIDATION, ba_sign_extend(), count, lag_aligned_input_sample(), n, sample_index(), and sample_is_in_segment_type().
Referenced by on_mark_validated_clicked(), and validation_segment_tests().
set_err()
static void set_err (char * err, size_t errsz, const char * fmt, ...) static
Definition at line 1633 of file bit_analysis.c.
References n.
Referenced by ba_session_load_json(), and ba_session_save_json().
json_write_escaped()
static void json_write_escaped (FILE * fp, const char * s) static
Definition at line 1643 of file bit_analysis.c.
References n.
Referenced by ba_session_save_json().
json_write_hex()
static void json_write_hex (FILE * fp, const uint8_t * data, size_t len) static
Definition at line 1667 of file bit_analysis.c.
References n.
Referenced by ba_session_save_json().
json_skip_ws()
static const char * json_skip_ws (const char * p, const char * end) static
Definition at line 1678 of file bit_analysis.c.
References n.
Referenced by json_find_key().
json_skip_string()
static const char * json_skip_string (const char * p, const char * end) static
Definition at line 1685 of file bit_analysis.c.
References n.
Referenced by json_find_key(), json_get_range(), and json_next_object().
json_find_key()
static const char * json_find_key (const char * start, const char * end, const char * key) static
Definition at line 1702 of file bit_analysis.c.
References json_skip_string(), json_skip_ws(), and n.
Referenced by json_get_bool(), json_get_double(), json_get_i64(), json_get_range(), json_get_string(), and json_get_u64().
json_get_range()
static int json_get_range (const char * start, const char * end, const char * key, char open, char close, const char ** out_start, const char ** out_end) static
Definition at line 1723 of file bit_analysis.c.
References json_find_key(), json_skip_string(), and n.
Referenced by ba_session_load_json().
json_next_object()
static int json_next_object (const char ** cursor, const char * end, const char ** obj_start, const char ** obj_end) static
Definition at line 1755 of file bit_analysis.c.
References json_skip_string(), and n.
Referenced by ba_session_load_json().
json_get_u64()
static int json_get_u64 (const char * start, const char * end, const char * key, uint64_t * out) static
Definition at line 1791 of file bit_analysis.c.
References json_find_key(), and n.
Referenced by ba_session_load_json(), json_get_bool(), parse_candidate_object(), parse_sample_object(), and parse_segment_object().
json_get_i64()
static int json_get_i64 (const char * start, const char * end, const char * key, int64_t * out) static
Definition at line 1808 of file bit_analysis.c.
References json_find_key(), and n.
Referenced by ba_session_load_json(), parse_candidate_object(), parse_sample_object(), and parse_segment_object().
json_get_double()
static int json_get_double (const char * start, const char * end, const char * key, double * out) static
Definition at line 1825 of file bit_analysis.c.
References json_find_key(), and n.
Referenced by ba_session_load_json(), parse_candidate_object(), parse_sample_object(), and parse_segment_object().
json_get_bool()
static int json_get_bool (const char * start, const char * end, const char * key, uint8_t * out) static
Definition at line 1842 of file bit_analysis.c.
References json_find_key(), json_get_u64(), and n.
Referenced by ba_session_load_json(), parse_candidate_object(), parse_sample_object(), and parse_segment_object().
json_get_string()
static int json_get_string (const char * start, const char * end, const char * key, char * out, size_t outsz) static
Definition at line 1866 of file bit_analysis.c.
References json_find_key(), and n.
Referenced by ba_session_load_json(), parse_candidate_object(), parse_sample_object(), and parse_segment_object().
hex_value()
static int hex_value (int ch) static
Definition at line 1908 of file bit_analysis.c.
References n.
Referenced by parse_hex_bytes().
parse_hex_bytes()
static size_t parse_hex_bytes (const char * hex, uint8_t * out, size_t outsz) static
Definition at line 1919 of file bit_analysis.c.
References hex_value(), and n.
Referenced by ba_session_load_json(), and parse_sample_object().
parse_segment_object()
static void parse_segment_object (const char * start, const char * end, ba_segment_t * seg) static
Definition at line 1935 of file bit_analysis.c.
References json_get_bool(), json_get_double(), json_get_i64(), json_get_string(), json_get_u64(), and n.
Referenced by ba_session_load_json().
parse_candidate_object()
static void parse_candidate_object (const char * start, const char * end, ba_candidate_t * c) static
Definition at line 1960 of file bit_analysis.c.
References json_get_bool(), json_get_double(), json_get_i64(), json_get_string(), json_get_u64(), and n.
Referenced by ba_session_load_json().
parse_sample_object()
static int parse_sample_object (const char * start, const char * end, ba_sample_t * sample) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 2042 of file bit_analysis.c.
References CANFD_DATA_MAX, json_get_bool(), json_get_double(), json_get_i64(), json_get_string(), json_get_u64(), n, and parse_hex_bytes().
Referenced by ba_session_load_json().
ba_session_save_json()
int ba_session_save_json (const ba_session_t * s, const char * path, char * err, size_t errsz)
Save a complete analysis session as JSON.
Parameters
s Session to write.
path Destination file path.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 2070 of file bit_analysis.c.
References ba_segment_type_name(), ba_session_state_name(), CANFD_DATA_MAX, json_write_escaped(), json_write_hex(), n, sample_index(), and set_err().
Referenced by candidate_tests(), mux_tests(), save_session_with_dialog(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_load_json()
int ba_session_load_json (ba_session_t * s, const char * path, char * err, size_t errsz)
Load an analysis session from JSON.
Parameters
s Destination session; replaced on success.
path Source file path.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 2281 of file bit_analysis.c.
References BA_DEFAULT_CAPACITY, BA_FD_MAX_BITS, ba_get_bit(), BA_MAX_CANDIDATES, BA_MAX_SEGMENTS, ba_session_analyze(), BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, ba_session_destroy(), ba_session_init(), BA_SESSION_PAUSED, CANFD_DATA_MAX, ba_sample_t::data, ba_sample_t::dlc, json_get_bool(), json_get_double(), json_get_i64(), json_get_range(), json_get_string(), json_get_u64(), json_next_object(), n, parse_candidate_object(), parse_hex_bytes(), parse_sample_object(), parse_segment_object(), set_err(), and ba_sample_t::timestamp_ns.
Referenced by candidate_tests(), mux_tests(), on_load_session_clicked(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_byte_order_name()
const char * ba_byte_order_name (ba_byte_order_t order)
Human-readable byte-order label.
Definition at line 2499 of file bit_analysis.c.
References BA_BYTE_ORDER_MOTOROLA, and n.
Referenced by refresh_candidate_store(), and refresh_inspector().
ba_segment_type_name()
const char * ba_segment_type_name (ba_segment_type_t type)
Human-readable segment-type label.
Definition at line 2504 of file bit_analysis.c.
References BA_SEGMENT_BASELINE, BA_SEGMENT_BOUNDARY, BA_SEGMENT_EVENT, BA_SEGMENT_RAMP, BA_SEGMENT_STATIC_STATE, BA_SEGMENT_STEP, BA_SEGMENT_TOGGLE, and BA_SEGMENT_VALIDATION.
Referenced by ba_session_save_json(), gui_create_bit_analysis_view(), on_add_marker_clicked(), and refresh_segment_store().
ba_input_type_name()
const char * ba_input_type_name (ba_input_type_t type)
Human-readable input-type label.
Definition at line 2519 of file bit_analysis.c.
References BA_INPUT_BOOLEAN, BA_INPUT_CONTINUOUS, BA_INPUT_ENUMERATED, and BA_INPUT_EVENT_ONLY.
ba_session_state_name()
const char * ba_session_state_name (ba_session_state_t state)
Human-readable session-state label.
Definition at line 2530 of file bit_analysis.c.
References BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, BA_SESSION_IDLE, BA_SESSION_PAUSED, BA_SESSION_READY, and BA_SESSION_REVIEW.
Referenced by ba_session_save_json(), and refresh_summary().