CANoScope: inc/bit_analysis.h File Reference
bit_analysis.h File Reference
GTK-independent engine for CAN payload bit analysis.
#include <stddef.h>
#include <stdint.h>
#include <time.h>
#include "can_message.h"
Data Structures
struct ba_sample_t
struct ba_segment_t
struct ba_bit_stats_t
struct ba_candidate_t
struct ba_session_t
Macros
#define BA_CLASSIC_MAX_BYTES 8
#define BA_CLASSIC_MAX_BITS 64
#define BA_FD_MAX_BYTES CANFD_DATA_MAX
#define BA_FD_MAX_BITS (CANFD_DATA_MAX * 8)
#define BA_LABEL_MAX 64
#define BA_UNIT_MAX 24
#define BA_NOTE_MAX 256
#define BA_DEFAULT_CAPACITY 200000u
#define BA_MAX_CANDIDATES 512u
#define BA_MAX_SEGMENTS 256u
Enumerations
enum ba_session_state_t {
BA_SESSION_IDLE = 0 , BA_SESSION_READY , BA_SESSION_CAPTURING , BA_SESSION_PAUSED ,
BA_SESSION_ANALYZING , BA_SESSION_REVIEW
}
enum ba_segment_type_t {
BA_SEGMENT_BASELINE = 0 , BA_SEGMENT_STATIC_STATE , BA_SEGMENT_TOGGLE , BA_SEGMENT_STEP ,
BA_SEGMENT_RAMP , BA_SEGMENT_BOUNDARY , BA_SEGMENT_VALIDATION , BA_SEGMENT_EVENT
}
enum ba_input_type_t { BA_INPUT_BOOLEAN = 0 , BA_INPUT_ENUMERATED , BA_INPUT_CONTINUOUS , BA_INPUT_EVENT_ONLY }
enum ba_byte_order_t { BA_BYTE_ORDER_INTEL = 0 , BA_BYTE_ORDER_MOTOROLA }
Functions
int ba_session_init (ba_session_t *s, size_t capacity)
Initialise a Bit Analysis session and allocate its sample ring.
void ba_session_destroy (ba_session_t *s)
Release memory owned by a Bit Analysis session.
void ba_session_reset (ba_session_t *s)
Reset samples, markers, baseline, and analysis results for a target.
void ba_session_configure_target (ba_session_t *s, uint32_t can_id, int is_extended, uint8_t expected_dlc)
Select the CAN identifier and DLC that the session should capture.
int ba_session_push_frame (ba_session_t *s, const can_msg_t *msg)
Filter and append one CAN frame to the target-frame ring buffer.
void ba_session_set_input (ba_session_t *s, ba_input_type_t type, const char *name, double value, const char *unit, int valid)
Set the current manual input value associated with subsequent frames.
uint32_t ba_session_add_segment (ba_session_t *s, ba_segment_type_t type, const char *label, double input_value, int input_valid, int64_t timestamp_ns)
Start a new experiment segment at a timestamp.
void ba_session_end_segment (ba_session_t *s, int64_t timestamp_ns)
Close the active experiment segment.
void ba_session_capture_baseline (ba_session_t *s)
Build a statistical baseline from baseline segments or all samples.
void ba_session_analyze (ba_session_t *s, uint8_t max_field_len)
Compute bit statistics and ranked field candidates.
int ba_candidate_validate_segments (const ba_session_t *s, const ba_candidate_t *c, double max_mean_absolute_error, size_t *sample_count_out, double *mean_absolute_error_out, double *max_absolute_error_out)
Validate a candidate against independent validation segments.
int ba_session_save_json (const ba_session_t *s, const char *path, char *err, size_t errsz)
Save a complete analysis session as JSON.
int ba_session_load_json (ba_session_t *s, const char *path, char *err, size_t errsz)
Load an analysis session from JSON.
int64_t ba_timespec_to_ns (const struct timespec *ts)
Convert a POSIX timespec to nanoseconds.
uint8_t ba_get_bit (const uint8_t *data, uint16_t bit)
Return one canonical LSB0 bit from a payload buffer.
uint64_t ba_extract_unsigned (const uint8_t *data, uint8_t dlc, uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from canonical coordinates.
uint64_t ba_extract_unsigned_dbc (const uint8_t *data, uint8_t dlc, uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from DBC start-bit coordinates.
int64_t ba_sign_extend (uint64_t raw, uint8_t bit_length)
Sign-extend an unsigned raw value as two's-complement.
uint16_t ba_canonical_to_dbc_start_bit (uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a canonical start bit to the corresponding DBC start bit.
uint16_t ba_dbc_to_canonical_start_bit (uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a DBC start bit to the canonical absolute start bit.
int ba_field_fits (uint16_t start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Return non-zero when a field fits inside the selected bit range.
const char * ba_byte_order_name (ba_byte_order_t order)
Human-readable byte-order label.
const char * ba_segment_type_name (ba_segment_type_t type)
Human-readable segment-type label.
const char * ba_input_type_name (ba_input_type_t type)
Human-readable input-type label.
const char * ba_session_state_name (ba_session_state_t state)
Human-readable session-state label.
Detailed Description
GTK-independent engine for CAN payload bit analysis.
Provides the data model and analysis API behind the Bit Analysis tab. The engine stores selected target frames in a preallocated ring buffer, tracks experiment segments and manual input values, computes per-bit statistics, scans candidate fields in Intel and Motorola byte order, estimates factor/offset, classifies protocol metadata, validates candidates on independent segments, and saves/loads analysis sessions as JSON.
Definition in file bit_analysis.h.
Macro Definition Documentation
BA_CLASSIC_MAX_BYTES
#define BA_CLASSIC_MAX_BYTES 8
Definition at line 22 of file bit_analysis.h.
BA_CLASSIC_MAX_BITS
#define BA_CLASSIC_MAX_BITS 64
Definition at line 23 of file bit_analysis.h.
BA_FD_MAX_BYTES
#define BA_FD_MAX_BYTES CANFD_DATA_MAX
Definition at line 24 of file bit_analysis.h.
BA_FD_MAX_BITS
#define BA_FD_MAX_BITS (CANFD_DATA_MAX * 8)
Definition at line 25 of file bit_analysis.h.
BA_LABEL_MAX
#define BA_LABEL_MAX 64
Definition at line 26 of file bit_analysis.h.
BA_UNIT_MAX
#define BA_UNIT_MAX 24
Definition at line 27 of file bit_analysis.h.
BA_NOTE_MAX
#define BA_NOTE_MAX 256
Definition at line 28 of file bit_analysis.h.
BA_DEFAULT_CAPACITY
#define BA_DEFAULT_CAPACITY 200000u
Definition at line 29 of file bit_analysis.h.
BA_MAX_CANDIDATES
#define BA_MAX_CANDIDATES 512u
Definition at line 30 of file bit_analysis.h.
BA_MAX_SEGMENTS
#define BA_MAX_SEGMENTS 256u
Definition at line 31 of file bit_analysis.h.
Enumeration Type Documentation
ba_session_state_t
enum ba_session_state_t
Enumerator
BA_SESSION_IDLE
BA_SESSION_READY
BA_SESSION_CAPTURING
BA_SESSION_PAUSED
BA_SESSION_ANALYZING
BA_SESSION_REVIEW
Definition at line 33 of file bit_analysis.h.
ba_segment_type_t
enum ba_segment_type_t
Enumerator
BA_SEGMENT_BASELINE
BA_SEGMENT_STATIC_STATE
BA_SEGMENT_TOGGLE
BA_SEGMENT_STEP
BA_SEGMENT_RAMP
BA_SEGMENT_BOUNDARY
BA_SEGMENT_VALIDATION
BA_SEGMENT_EVENT
Definition at line 42 of file bit_analysis.h.
ba_input_type_t
enum ba_input_type_t
Enumerator
BA_INPUT_BOOLEAN
BA_INPUT_ENUMERATED
BA_INPUT_CONTINUOUS
BA_INPUT_EVENT_ONLY
Definition at line 53 of file bit_analysis.h.
ba_byte_order_t
enum ba_byte_order_t
Enumerator
BA_BYTE_ORDER_INTEL
BA_BYTE_ORDER_MOTOROLA
Definition at line 60 of file bit_analysis.h.
Function Documentation
ba_session_init()
int ba_session_init (ba_session_t * s, size_t capacity)
Initialise a Bit Analysis session and allocate its sample ring.
Parameters
s Session object to initialise.
capacity Ring capacity in target frames; 0 uses BA_DEFAULT_CAPACITY.
Returns
0 on success, -1 on allocation or argument failure.
Definition at line 339 of file bit_analysis.c.
References ba_session_t::active_segment, BA_CLASSIC_MAX_BYTES, BA_DEFAULT_CAPACITY, BA_INPUT_CONTINUOUS, BA_SESSION_IDLE, ba_session_t::expected_dlc, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, ba_session_t::next_segment_id, safe_copy(), ba_session_t::sample_capacity, ba_session_t::samples, and ba_session_t::state.
Referenced by ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), gui_create_bit_analysis_view(), lag_tests(), motorola_candidate_tests(), mux_tests(), on_analyze_clicked(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_destroy()
void ba_session_destroy (ba_session_t * s)
Release memory owned by a Bit Analysis session.
Parameters
s Session to destroy; may be NULL.
Definition at line 362 of file bit_analysis.c.
References ba_session_t::samples.
Referenced by analysis_done_idle(), ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_reset()
void ba_session_reset (ba_session_t * s)
Reset samples, markers, baseline, and analysis results for a target.
Parameters
s Session to reset while preserving allocated storage and settings.
Definition at line 370 of file bit_analysis.c.
References ba_session_t::accept_varying_dlc, ba_session_t::active_segment, ba_session_t::analyze_fd_payload, BA_LABEL_MAX, BA_SESSION_READY, BA_UNIT_MAX, ba_session_t::can_id, ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::expected_dlc, ba_session_t::include_rx, ba_session_t::include_tx, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, ba_session_t::is_extended, ba_session_t::next_segment_id, safe_copy(), ba_session_t::sample_capacity, samples, ba_session_t::samples, and ba_session_t::state.
Referenced by ba_session_configure_target().
ba_session_configure_target()
void ba_session_configure_target (ba_session_t * s, uint32_t can_id, int is_extended, uint8_t expected_dlc)
Select the CAN identifier and DLC that the session should capture.
Parameters
s Session to configure.
can_id Standard or extended CAN identifier.
is_extended Non-zero for a 29-bit identifier.
expected_dlc Expected payload length in bytes.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 409 of file bit_analysis.c.
References ba_session_reset(), ba_session_t::can_id, CANFD_DATA_MAX, ba_session_t::expected_dlc, and ba_session_t::is_extended.
Referenced by apply_controls_to_session(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), on_analyze_clicked(), on_reset_clicked(), on_target_changed(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_push_frame()
int ba_session_push_frame (ba_session_t * s, const can_msg_t * msg)
Filter and append one CAN frame to the target-frame ring buffer.
Parameters
s Active session.
msg CAN/CAN FD frame to evaluate.
Returns
1 when the frame was accepted and copied, otherwise 0.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 499 of file bit_analysis.c.
References ba_session_t::active_segment, BA_SESSION_CAPTURING, ba_timespec_to_ns(), CANFD_DATA_MAX, ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_sample_t::data, can_msg_t::data, ba_sample_t::direction, can_msg_t::direction, ba_sample_t::dlc, can_msg_t::dlc, ba_session_t::dropped_samples, ba_session_t::first_ts_ns, ba_segment_t::id, ba_sample_t::input_valid, ba_sample_t::input_value, ba_session_t::latest_data, ba_session_t::latest_dlc, ba_session_t::latest_ts_ns, matches_target(), ba_session_t::sample_capacity, ba_session_t::sample_count, ba_session_t::sample_head, ba_session_t::samples, ba_session_t::segment_count, ba_sample_t::segment_id, ba_session_t::segments, can_msg_t::seq, ba_sample_t::sequence, ba_session_t::state, can_msg_t::timestamp, ba_sample_t::timestamp_ns, and ba_session_t::total_target_frames.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), fast_path_tests(), gui_bit_analysis_handle_message(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_set_input()
void ba_session_set_input (ba_session_t * s, ba_input_type_t type, const char * name, double value, const char * unit, int valid)
Set the current manual input value associated with subsequent frames.
Parameters
s Active session.
type Input channel type.
name Human-readable input name.
value Numeric input value.
unit Engineering unit.
valid Non-zero when value is meaningful for fitting.
Definition at line 423 of file bit_analysis.c.
References ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_session_t::input_name, ba_session_t::input_type, ba_session_t::input_unit, safe_copy(), and value.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), lag_tests(), motorola_candidate_tests(), signed_candidate_tests(), sync_input_to_session(), transition_match_tests(), and validation_segment_tests().
ba_session_add_segment()
uint32_t ba_session_add_segment (ba_session_t * s, ba_segment_type_t type, const char * label, double input_value, int input_valid, int64_t timestamp_ns)
Start a new experiment segment at a timestamp.
Parameters
s Active session.
type Segment type.
label Optional user-visible label.
input_value Input value assigned to the segment.
input_valid Non-zero if input_value should be used.
timestamp_ns Segment start timestamp in nanoseconds.
Returns
Non-zero segment id on success, 0 when no segment slot is available.
Definition at line 439 of file bit_analysis.c.
References ba_session_t::active_segment, BA_MAX_SEGMENTS, ba_session_end_segment(), ba_session_t::current_input_valid, ba_session_t::current_input_value, ba_segment_t::first_sample, ba_segment_t::id, ba_segment_t::input_valid, ba_segment_t::input_value, label, ba_segment_t::label, ba_session_t::latest_ts_ns, ba_session_t::next_segment_id, safe_copy(), ba_session_t::segment_count, ba_session_t::segments, ba_segment_t::start_ns, ba_session_t::total_target_frames, and ba_segment_t::type.
Referenced by baseline_segment_tests(), candidate_tests(), on_add_marker_clicked(), and validation_segment_tests().
ba_session_end_segment()
void ba_session_end_segment (ba_session_t * s, int64_t timestamp_ns)
Close the active experiment segment.
Parameters
s Active session.
timestamp_ns End timestamp in nanoseconds; 0 uses latest sample time.
Definition at line 468 of file bit_analysis.c.
References ba_session_t::active_segment, ba_segment_t::end_ns, ba_segment_t::first_sample, ba_session_t::latest_ts_ns, ba_segment_t::sample_count, ba_session_t::segment_count, ba_session_t::segments, and ba_session_t::total_target_frames.
Referenced by ba_session_add_segment(), baseline_segment_tests(), candidate_tests(), on_end_marker_clicked(), and validation_segment_tests().
ba_session_capture_baseline()
void ba_session_capture_baseline (ba_session_t * s)
Build a statistical baseline from baseline segments or all samples.
Parameters
s Active session with target samples.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 558 of file bit_analysis.c.
References BA_FD_MAX_BITS, ba_get_bit(), ba_session_t::baseline_bits, ba_session_t::baseline_data, ba_session_t::baseline_sample_count, ba_session_t::baseline_valid, ba_sample_t::data, ba_session_t::expected_dlc, ba_session_t::latest_dlc, ba_session_t::sample_count, sample_index(), sample_is_in_baseline_segment(), ba_session_t::samples, and session_has_baseline_segment().
Referenced by baseline_segment_tests(), candidate_tests(), and on_baseline_clicked().
ba_session_analyze()
void ba_session_analyze (ba_session_t * s, uint8_t max_field_len)
Compute bit statistics and ranked field candidates.
Parameters
s Active session.
max_field_len Maximum contiguous field length to scan in bits.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 1455 of file bit_analysis.c.
References BA_ANALYZE_MAX_SAMPLES, BA_BYTE_ORDER_INTEL, BA_BYTE_ORDER_MOTOROLA, BA_CLASSIC_MAX_BYTES, ba_dbc_to_canonical_start_bit(), BA_FD_MAX_BYTES, ba_field_fits(), BA_INVALID_BIT, BA_SESSION_ANALYZING, BA_SESSION_REVIEW, cmp_candidate_desc(), collect_analysis_samples(), compute_bit_stats(), evaluate_candidate(), n, and samples.
Referenced by analysis_thread_main(), ba_session_load_json(), baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_candidate_validate_segments()
int ba_candidate_validate_segments (const ba_session_t * s, const ba_candidate_t * c, double max_mean_absolute_error, size_t * sample_count_out, double * mean_absolute_error_out, double * max_absolute_error_out)
Validate a candidate against independent validation segments.
Parameters
s Session containing validation samples.
c Candidate to validate.
max_mean_absolute_error Negative for automatic tolerance.
sample_count_out Optional validated sample count output.
mean_absolute_error_out Optional validation MAE output.
max_absolute_error_out Optional validation max-error output.
Returns
1 when validation passes, otherwise 0.
Definition at line 1571 of file bit_analysis.c.
References ba_extract_unsigned_dbc(), BA_SEGMENT_VALIDATION, ba_sign_extend(), count, lag_aligned_input_sample(), n, sample_index(), and sample_is_in_segment_type().
Referenced by on_mark_validated_clicked(), and validation_segment_tests().
ba_session_save_json()
int ba_session_save_json (const ba_session_t * s, const char * path, char * err, size_t errsz)
Save a complete analysis session as JSON.
Parameters
s Session to write.
path Destination file path.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 2070 of file bit_analysis.c.
References ba_segment_type_name(), ba_session_state_name(), CANFD_DATA_MAX, json_write_escaped(), json_write_hex(), n, sample_index(), and set_err().
Referenced by candidate_tests(), mux_tests(), save_session_with_dialog(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_session_load_json()
int ba_session_load_json (ba_session_t * s, const char * path, char * err, size_t errsz)
Load an analysis session from JSON.
Parameters
s Destination session; replaced on success.
path Source file path.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 2281 of file bit_analysis.c.
References BA_DEFAULT_CAPACITY, BA_FD_MAX_BITS, ba_get_bit(), BA_MAX_CANDIDATES, BA_MAX_SEGMENTS, ba_session_analyze(), BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, ba_session_destroy(), ba_session_init(), BA_SESSION_PAUSED, CANFD_DATA_MAX, ba_sample_t::data, ba_sample_t::dlc, json_get_bool(), json_get_double(), json_get_i64(), json_get_range(), json_get_string(), json_get_u64(), json_next_object(), n, parse_candidate_object(), parse_hex_bytes(), parse_sample_object(), parse_segment_object(), set_err(), and ba_sample_t::timestamp_ns.
Referenced by candidate_tests(), mux_tests(), on_load_session_clicked(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
ba_timespec_to_ns()
int64_t ba_timespec_to_ns (const struct timespec * ts)
Convert a POSIX timespec to nanoseconds.
Definition at line 61 of file bit_analysis.c.
Referenced by ba_session_push_frame(), and update_survey().
ba_get_bit()
uint8_t ba_get_bit (const uint8_t * data, uint16_t bit)
Return one canonical LSB0 bit from a payload buffer.
Definition at line 68 of file bit_analysis.c.
Referenced by ba_extract_unsigned_dbc(), ba_session_capture_baseline(), ba_session_load_json(), cell_score_for_bit(), compute_bit_stats(), mux_score_for_values(), on_matrix_draw(), and refresh_bit_stats_label().
ba_extract_unsigned()
uint64_t ba_extract_unsigned (const uint8_t * data, uint8_t dlc, uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from canonical coordinates.
Parameters
data Payload bytes.
dlc Payload length in bytes.
canonical_start_bit Byte0/bit0 absolute start coordinate.
bit_length Field length in bits.
order Intel or Motorola byte order.
Returns
Extracted raw value, or 0 when the field does not fit.
Definition at line 170 of file bit_analysis.c.
References ba_canonical_to_dbc_start_bit(), ba_extract_unsigned_dbc(), and BA_INVALID_BIT.
Referenced by candidate_tests(), extraction_tests(), on_timeline_draw(), and refresh_field_preview().
ba_extract_unsigned_dbc()
uint64_t ba_extract_unsigned_dbc (const uint8_t * data, uint8_t dlc, uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order)
Extract a raw unsigned value from DBC start-bit coordinates.
Definition at line 137 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_field_fits(), ba_get_bit(), and value.
Referenced by ba_candidate_validate_segments(), ba_extract_unsigned(), and evaluate_candidate().
ba_sign_extend()
int64_t ba_sign_extend (uint64_t raw, uint8_t bit_length)
Sign-extend an unsigned raw value as two's-complement.
Definition at line 185 of file bit_analysis.c.
Referenced by ba_candidate_validate_segments(), evaluate_candidate(), extraction_tests(), on_timeline_draw(), refresh_field_preview(), and validate_candidate_dbc_roundtrip().
ba_canonical_to_dbc_start_bit()
uint16_t ba_canonical_to_dbc_start_bit (uint16_t canonical_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a canonical start bit to the corresponding DBC start bit.
Definition at line 118 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_dbc_to_canonical_start_bit(), ba_field_fits(), and BA_INVALID_BIT.
Referenced by ba_extract_unsigned(), and extraction_tests().
ba_dbc_to_canonical_start_bit()
uint16_t ba_dbc_to_canonical_start_bit (uint16_t dbc_start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Convert a DBC start bit to the canonical absolute start bit.
Definition at line 95 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_field_fits(), and BA_INVALID_BIT.
Referenced by ba_canonical_to_dbc_start_bit(), ba_session_analyze(), and extraction_tests().
ba_field_fits()
int ba_field_fits (uint16_t start_bit, uint8_t bit_length, ba_byte_order_t order, uint16_t total_bits)
Return non-zero when a field fits inside the selected bit range.
Definition at line 73 of file bit_analysis.c.
References BA_BYTE_ORDER_INTEL.
Referenced by ba_canonical_to_dbc_start_bit(), ba_dbc_to_canonical_start_bit(), ba_extract_unsigned_dbc(), and ba_session_analyze().
ba_byte_order_name()
const char * ba_byte_order_name (ba_byte_order_t order)
Human-readable byte-order label.
Definition at line 2499 of file bit_analysis.c.
References BA_BYTE_ORDER_MOTOROLA, and n.
Referenced by refresh_candidate_store(), and refresh_inspector().
ba_segment_type_name()
const char * ba_segment_type_name (ba_segment_type_t type)
Human-readable segment-type label.
Definition at line 2504 of file bit_analysis.c.
References BA_SEGMENT_BASELINE, BA_SEGMENT_BOUNDARY, BA_SEGMENT_EVENT, BA_SEGMENT_RAMP, BA_SEGMENT_STATIC_STATE, BA_SEGMENT_STEP, BA_SEGMENT_TOGGLE, and BA_SEGMENT_VALIDATION.
Referenced by ba_session_save_json(), gui_create_bit_analysis_view(), on_add_marker_clicked(), and refresh_segment_store().
ba_input_type_name()
const char * ba_input_type_name (ba_input_type_t type)
Human-readable input-type label.
Definition at line 2519 of file bit_analysis.c.
References BA_INPUT_BOOLEAN, BA_INPUT_CONTINUOUS, BA_INPUT_ENUMERATED, and BA_INPUT_EVENT_ONLY.
ba_session_state_name()
const char * ba_session_state_name (ba_session_state_t state)
Human-readable session-state label.
Definition at line 2530 of file bit_analysis.c.
References BA_SESSION_ANALYZING, BA_SESSION_CAPTURING, BA_SESSION_IDLE, BA_SESSION_PAUSED, BA_SESSION_READY, and BA_SESSION_REVIEW.
Referenced by ba_session_save_json(), and refresh_summary().