CANoScope: gui/db_creation.c File Reference
db_creation.c File Reference
DB Creation tab for building/updating DBC files from live RX rows.
#include <ctype.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/dbc.h"
Data Structures
struct graph_sample_t
Macros
#define RAW_TEXT_MAX ((CANFD_DATA_MAX * 2u) + 1u)
#define GRAPH_MAX_SAMPLES 2048
#define GRAPH_WINDOW_SEC 20.0
Enumerations
enum {
MCOL_LABEL = 0 , MCOL_ID , MCOL_EXT , MCOL_DLC ,
MCOL_RAW , MCOL_NUM
}
Functions
static void db_creation_refresh_messages (void)
static void update_sample_preview (void)
static void graph_clear (void)
static void set_status (const char *fmt,...)
static void fmt_double (char *buf, size_t sz, double v)
static void set_comment_text (const char *text)
static void get_comment_text (char *out, size_t outsz)
static void format_raw_data (char *buf, size_t sz, const uint8_t *data, uint8_t dlc)
static int hex_value (char c)
static void parse_raw_data (const char *raw, uint8_t *out, uint8_t dlc)
static void default_message_name (char *buf, size_t sz, uint32_t id, int is_ext)
static gboolean normalize_name (const char *input, const char *fallback, char out[64])
static gboolean get_selected_message (uint32_t *id, int *is_ext, uint8_t *dlc, uint8_t data[64], char *data_text, size_t data_text_sz)
static gboolean signal_fits_payload (uint16_t start_bit, uint16_t length, int little_endian, uint8_t dlc)
static void read_decode_signal (dbc_signal_t *sig)
static int graph_sample_index (int logical)
static void graph_append (double value)
static void graph_draw_text (cairo_t *cr, const char *text, double x, double y)
static gboolean on_graph_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
static void selected_message_changed (GtkComboBox *combo, gpointer data)
static void signal_form_changed (GtkWidget *w, gpointer data)
static gboolean refresh_timer_cb (gpointer data)
void gui_db_creation_trace_changed (void)
Notify the DB Creation tab that the trace RX list may have changed.
void gui_db_creation_handle_message (const can_msg_t *msg)
Feed one received frame to the DB Creation live preview graph.
void gui_db_creation_prefill_signal (uint32_t message_id, int is_extended, uint8_t dlc, const char *signal_name, uint16_t start_bit, uint8_t bit_length, int byte_order, int is_signed, double factor, double offset, double minimum, double maximum, const char *unit, const char *comment)
Pre-fill DB Creation from a Bit Analysis candidate.
static void on_refresh_clicked (GtkWidget *button, gpointer data)
static void add_dbc_filter (GtkWidget *dlg)
static void on_new_db (GtkWidget *button, gpointer data)
static void on_open_db (GtkWidget *button, gpointer data)
static void on_use_loaded_db (GtkWidget *button, gpointer data)
static gboolean build_signal_from_form (dbc_signal_t *sig, uint8_t dlc, char *err, size_t errsz)
static void on_save_signal (GtkWidget *button, gpointer data)
static GtkWidget * grid_label (const char *text)
static GtkWidget * new_double_spin (double value, int digits)
GtkWidget * gui_create_db_creation_view (void)
Build the DB Creation tab for creating/updating DBC files from RX rows.
Variables
struct {
GtkWidget * target_entry
GtkWidget * msg_combo
GtkListStore * msg_store
GtkWidget * rx_count_label
GtkWidget * message_name_entry
GtkWidget * signal_name_entry
GtkWidget * start_spin
GtkWidget * length_spin
GtkWidget * endian_combo
GtkWidget * signed_check
GtkWidget * factor_spin
GtkWidget * offset_spin
GtkWidget * min_spin
GtkWidget * max_spin
GtkWidget * unit_entry
GtkWidget * comment_view
GtkWidget * sample_data_label
GtkWidget * sample_raw_label
GtkWidget * sample_value_label
GtkWidget * graph_area
GtkWidget * status_label
guint refresh_source
gboolean preserve_form_on_refresh
gboolean refreshing_messages
graph_sample_t graph_samples [2048]
int graph_head
int graph_count
gint64 graph_start_us
uint32_t selected_id
int selected_ext
gboolean selected_valid
} s_tab
Detailed Description
DB Creation tab for building/updating DBC files from live RX rows.
Definition in file db_creation.c.
Macro Definition Documentation
RAW_TEXT_MAX
#define RAW_TEXT_MAX ((CANFD_DATA_MAX * 2u) + 1u)
Definition at line 17 of file db_creation.c.
GRAPH_MAX_SAMPLES
#define GRAPH_MAX_SAMPLES 2048
Definition at line 18 of file db_creation.c.
GRAPH_WINDOW_SEC
#define GRAPH_WINDOW_SEC 20.0
Definition at line 19 of file db_creation.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MCOL_LABEL
MCOL_ID
MCOL_EXT
MCOL_DLC
MCOL_RAW
MCOL_NUM
Definition at line 26 of file db_creation.c.
Function Documentation
db_creation_refresh_messages()
static void db_creation_refresh_messages (void) static
< Maximum payload of a CAN FD frame.
Definition at line 749 of file db_creation.c.
References format_raw_data(), get_selected_message(), graph_clear(), gui_trace_collect_rx_messages(), GUI_TRACE_DATA_TEXT_MAX, label, MCOL_DLC, MCOL_EXT, MCOL_ID, MCOL_LABEL, MCOL_RAW, n, RAW_TEXT_MAX, rows, s_tab, and selected_message_changed().
Referenced by gui_create_db_creation_view(), gui_db_creation_prefill_signal(), on_refresh_clicked(), and refresh_timer_cb().
update_sample_preview()
static void update_sample_preview (void) static
< Maximum payload of a CAN FD frame.
Definition at line 529 of file db_creation.c.
References CANFD_DATA_MAX, dbc_decode_physical(), dbc_extract_raw(), fmt_double(), get_selected_message(), GUI_TRACE_DATA_TEXT_MAX, label, n, read_decode_signal(), s_tab, sig, and signal_fits_payload().
Referenced by gui_db_creation_prefill_signal(), selected_message_changed(), and signal_form_changed().
graph_clear()
static void graph_clear (void) static
Definition at line 287 of file db_creation.c.
References n, and s_tab.
Referenced by db_creation_refresh_messages(), gui_db_creation_prefill_signal(), selected_message_changed(), and signal_form_changed().
set_status()
static void set_status (const char * fmt, ...) static
Definition at line 73 of file db_creation.c.
References n, and s_tab.
Referenced by gui_db_creation_prefill_signal(), on_save_signal(), and on_use_loaded_db().
fmt_double()
static void fmt_double (char * buf, size_t sz, double v) static
Definition at line 86 of file db_creation.c.
References n.
Referenced by gui_db_creation_handle_message(), and update_sample_preview().
set_comment_text()
static void set_comment_text (const char * text) static
Definition at line 99 of file db_creation.c.
References n, and s_tab.
Referenced by gui_db_creation_prefill_signal().
get_comment_text()
static void get_comment_text (char * out, size_t outsz) static
Definition at line 108 of file db_creation.c.
References n, and s_tab.
Referenced by build_signal_from_form().
format_raw_data()
static void format_raw_data (char * buf, size_t sz, const uint8_t * data, uint8_t dlc) static
Definition at line 124 of file db_creation.c.
References n.
Referenced by db_creation_refresh_messages().
hex_value()
static int hex_value (char c) static
Definition at line 135 of file db_creation.c.
References n.
Referenced by parse_raw_data().
parse_raw_data()
static void parse_raw_data (const char * raw, uint8_t * out, uint8_t dlc) static
Definition at line 143 of file db_creation.c.
References hex_value(), and n.
Referenced by get_selected_message().
default_message_name()
static void default_message_name (char * buf, size_t sz, uint32_t id, int is_ext) static
Definition at line 156 of file db_creation.c.
References n.
Referenced by gui_db_creation_prefill_signal(), on_save_signal(), and selected_message_changed().
normalize_name()
static gboolean normalize_name (const char * input, const char * fallback, char out[64/**< Max message/signal name length. */]) static
< Max message/signal name length.
Definition at line 165 of file db_creation.c.
References DBC_NAME_MAX, and n.
Referenced by build_signal_from_form(), and on_save_signal().
get_selected_message()
static gboolean get_selected_message (uint32_t * id, int * is_ext, uint8_t * dlc, uint8_t data[64/**< Maximum payload of a CAN FD frame. */], char * data_text, size_t data_text_sz) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 194 of file db_creation.c.
References CANFD_DATA_MAX, label, MCOL_DLC, MCOL_EXT, MCOL_ID, MCOL_LABEL, MCOL_RAW, n, parse_raw_data(), and s_tab.
Referenced by db_creation_refresh_messages(), gui_db_creation_handle_message(), on_save_signal(), selected_message_changed(), and update_sample_preview().
signal_fits_payload()
static gboolean signal_fits_payload (uint16_t start_bit, uint16_t length, int little_endian, uint8_t dlc) static
Definition at line 239 of file db_creation.c.
References n.
Referenced by build_signal_from_form(), gui_db_creation_handle_message(), and update_sample_preview().
read_decode_signal()
static void read_decode_signal (dbc_signal_t * sig) static
Definition at line 264 of file db_creation.c.
References n, s_tab, and sig.
Referenced by gui_db_creation_handle_message(), and update_sample_preview().
graph_sample_index()
static int graph_sample_index (int logical) static
Definition at line 281 of file db_creation.c.
References GRAPH_MAX_SAMPLES, n, and s_tab.
Referenced by on_graph_draw().
graph_append()
static void graph_append (double value) static
Definition at line 296 of file db_creation.c.
References GRAPH_MAX_SAMPLES, n, s_tab, and value.
Referenced by gui_db_creation_handle_message().
graph_draw_text()
static void graph_draw_text (cairo_t * cr, const char * text, double x, double y) static
Definition at line 314 of file db_creation.c.
References n.
Referenced by on_graph_draw().
on_graph_draw()
static gboolean on_graph_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Definition at line 320 of file db_creation.c.
References graph_draw_text(), graph_sample_index(), GRAPH_WINDOW_SEC, label, last_x, last_y, n, s_tab, and graph_sample_t::value.
Referenced by gui_create_db_creation_view().
selected_message_changed()
static void selected_message_changed (GtkComboBox * combo, gpointer data) static
< Max message/signal name length.
Definition at line 460 of file db_creation.c.
References dbc_find_message(), dbc_free(), dbc_load_file(), DBC_NAME_MAX, default_message_name(), get_selected_message(), graph_clear(), n, s_tab, and update_sample_preview().
Referenced by db_creation_refresh_messages(), gui_create_db_creation_view(), on_open_db(), and on_use_loaded_db().
signal_form_changed()
static void signal_form_changed (GtkWidget * w, gpointer data) static
Definition at line 572 of file db_creation.c.
References graph_clear(), n, and update_sample_preview().
Referenced by gui_create_db_creation_view().
refresh_timer_cb()
static gboolean refresh_timer_cb (gpointer data) static
Definition at line 580 of file db_creation.c.
References db_creation_refresh_messages(), n, and s_tab.
Referenced by gui_db_creation_trace_changed().
gui_db_creation_trace_changed()
void gui_db_creation_trace_changed (void)
Notify the DB Creation tab that the trace RX list may have changed.
Definition at line 588 of file db_creation.c.
References n, refresh_timer_cb(), and s_tab.
Referenced by gui_add_message(), and gui_clear_trace().
gui_db_creation_handle_message()
void gui_db_creation_handle_message (const can_msg_t * msg)
Feed one received frame to the DB Creation live preview graph.
Parameters
msg RX frame; ignored unless it matches the selected source message.
< Frame direction: received.
Definition at line 596 of file db_creation.c.
References CAN_DIR_RX, dbc_decode_physical(), dbc_extract_raw(), fmt_double(), get_selected_message(), graph_append(), gui_format_data(), gui_format_id(), GUI_TRACE_DATA_TEXT_MAX, GUI_TRACE_ID_TEXT_MAX, n, read_decode_signal(), s_tab, sig, and signal_fits_payload().
Referenced by gui_add_message().
gui_db_creation_prefill_signal()
void gui_db_creation_prefill_signal (uint32_t message_id, int is_extended, uint8_t dlc, const char * signal_name, uint16_t start_bit, uint8_t bit_length, int byte_order, int is_signed, double factor, double offset, double minimum, double maximum, const char * unit, const char * comment)
Pre-fill DB Creation from a Bit Analysis candidate.
Parameters
message_id Raw CAN identifier.
is_extended Non-zero for extended CAN ID.
dlc Message DLC.
signal_name Proposed signal name.
start_bit DBC start bit.
bit_length Signal bit length.
byte_order Non-zero for Intel/little-endian, zero for Motorola.
is_signed Non-zero for signed two's-complement.
factor DBC factor.
offset DBC offset.
minimum Physical minimum.
maximum Physical maximum.
unit Engineering unit.
comment Optional DBC signal comment/evidence.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Max message/signal name length.
Definition at line 641 of file db_creation.c.
References CANFD_DATA_MAX, gui_widgets_t::db_creation_page, db_creation_refresh_messages(), DBC_NAME_MAX, default_message_name(), g_gui, graph_clear(), gui_format_id(), gui_signal_get_dbc_path(), gui_status_message(), GUI_TRACE_DATA_TEXT_MAX, GUI_TRACE_ID_TEXT_MAX, label, gui_widgets_t::main_notebook, MCOL_DLC, MCOL_EXT, MCOL_ID, MCOL_LABEL, MCOL_RAW, n, s_tab, set_comment_text(), set_status(), and update_sample_preview().
Referenced by on_promote_clicked().
on_refresh_clicked()
static void on_refresh_clicked (GtkWidget * button, gpointer data) static
Definition at line 826 of file db_creation.c.
References db_creation_refresh_messages(), and n.
Referenced by gui_create_db_creation_view().
add_dbc_filter()
static void add_dbc_filter (GtkWidget * dlg) static
Definition at line 833 of file db_creation.c.
References n.
Referenced by on_new_db(), and on_open_db().
on_new_db()
static void on_new_db (GtkWidget * button, gpointer data) static
Definition at line 841 of file db_creation.c.
References add_dbc_filter(), g_gui, n, s_tab, and gui_widgets_t::window.
Referenced by gui_create_db_creation_view().
on_open_db()
static void on_open_db (GtkWidget * button, gpointer data) static
Definition at line 868 of file db_creation.c.
References add_dbc_filter(), g_gui, n, s_tab, selected_message_changed(), and gui_widgets_t::window.
Referenced by gui_create_db_creation_view().
on_use_loaded_db()
static void on_use_loaded_db (GtkWidget * button, gpointer data) static
Definition at line 892 of file db_creation.c.
References gui_signal_get_dbc_path(), n, s_tab, selected_message_changed(), and set_status().
Referenced by gui_create_db_creation_view().
build_signal_from_form()
static gboolean build_signal_from_form (dbc_signal_t * sig, uint8_t dlc, char * err, size_t errsz) static
Definition at line 905 of file db_creation.c.
References get_comment_text(), n, normalize_name(), s_tab, sig, signal_fits_payload(), and plot_signal_t::unit.
Referenced by on_save_signal().
on_save_signal()
static void on_save_signal (GtkWidget * button, gpointer data) static
< Max message/signal name length.
< Max message/signal name length.
Definition at line 948 of file db_creation.c.
References build_signal_from_form(), dbc_create_empty(), dbc_free(), dbc_load_file(), DBC_NAME_MAX, dbc_save_file(), dbc_upsert_message(), dbc_upsert_signal(), default_message_name(), get_selected_message(), gui_signal_load_dbc(), gui_status_message(), n, normalize_name(), s_tab, set_status(), and sig.
Referenced by gui_create_db_creation_view().
grid_label()
static GtkWidget * grid_label (const char * text) static
Definition at line 1032 of file db_creation.c.
References label, and n.
Referenced by gui_create_db_creation_view().
new_double_spin()
static GtkWidget * new_double_spin (double value, int digits) static
Definition at line 1040 of file db_creation.c.
References n, and value.
Referenced by gui_create_db_creation_view().
gui_create_db_creation_view()
GtkWidget * gui_create_db_creation_view (void)
Build the DB Creation tab for creating/updating DBC files from RX rows.
Returns
A container widget for use as a notebook page.
< Max signal unit string length.
Definition at line 1051 of file db_creation.c.
References db_creation_refresh_messages(), DBC_UNIT_MAX, grid_label(), MCOL_LABEL, MCOL_NUM, n, new_double_spin(), on_graph_draw(), on_new_db(), on_open_db(), on_refresh_clicked(), on_save_signal(), on_use_loaded_db(), s_tab, selected_message_changed(), sig, and signal_form_changed().
Referenced by gui_create_main_window().
Variable Documentation
target_entry
GtkWidget* target_entry
Definition at line 36 of file db_creation.c.
msg_combo
GtkWidget* msg_combo
Definition at line 37 of file db_creation.c.
msg_store
GtkListStore* msg_store
Definition at line 38 of file db_creation.c.
rx_count_label
GtkWidget* rx_count_label
Definition at line 39 of file db_creation.c.
message_name_entry
GtkWidget* message_name_entry
Definition at line 40 of file db_creation.c.
signal_name_entry
GtkWidget* signal_name_entry
Definition at line 41 of file db_creation.c.
start_spin
GtkWidget* start_spin
Definition at line 42 of file db_creation.c.
length_spin
GtkWidget* length_spin
Definition at line 43 of file db_creation.c.
endian_combo
GtkWidget* endian_combo
Definition at line 44 of file db_creation.c.
signed_check
GtkWidget* signed_check
Definition at line 45 of file db_creation.c.
factor_spin
GtkWidget* factor_spin
Definition at line 46 of file db_creation.c.
offset_spin
GtkWidget* offset_spin
Definition at line 47 of file db_creation.c.
min_spin
GtkWidget* min_spin
Definition at line 48 of file db_creation.c.
max_spin
GtkWidget* max_spin
Definition at line 49 of file db_creation.c.
unit_entry
GtkWidget* unit_entry
Definition at line 50 of file db_creation.c.
comment_view
GtkWidget* comment_view
Definition at line 51 of file db_creation.c.
sample_data_label
GtkWidget* sample_data_label
Definition at line 52 of file db_creation.c.
sample_raw_label
GtkWidget* sample_raw_label
Definition at line 53 of file db_creation.c.
sample_value_label
GtkWidget* sample_value_label
Definition at line 54 of file db_creation.c.
graph_area
GtkWidget* graph_area
Definition at line 55 of file db_creation.c.
status_label
GtkWidget* status_label
Definition at line 56 of file db_creation.c.
refresh_source
guint refresh_source
Definition at line 57 of file db_creation.c.
preserve_form_on_refresh
gboolean preserve_form_on_refresh
Definition at line 58 of file db_creation.c.
refreshing_messages
gboolean refreshing_messages
Definition at line 59 of file db_creation.c.
graph_samples
graph_sample_t graph_samples[2048]
Definition at line 60 of file db_creation.c.
graph_head
int graph_head
Definition at line 61 of file db_creation.c.
graph_count
int graph_count
Definition at line 62 of file db_creation.c.
graph_start_us
gint64 graph_start_us
Definition at line 63 of file db_creation.c.
selected_id
uint32_t selected_id
Definition at line 64 of file db_creation.c.
selected_ext
int selected_ext
Definition at line 65 of file db_creation.c.
selected_valid
gboolean selected_valid
Definition at line 66 of file db_creation.c.
[struct]
struct { ... } s_tab
Referenced by build_signal_from_form(), db_creation_refresh_messages(), get_comment_text(), get_selected_message(), graph_append(), graph_clear(), graph_sample_index(), gui_create_db_creation_view(), gui_db_creation_handle_message(), gui_db_creation_prefill_signal(), gui_db_creation_trace_changed(), on_graph_draw(), on_new_db(), on_open_db(), on_save_signal(), on_use_loaded_db(), read_decode_signal(), refresh_timer_cb(), selected_message_changed(), set_comment_text(), set_status(), and update_sample_preview().