CANoScope: driver/dbc.c File Reference
dbc.c File Reference
DBC (CAN database) parser and signal-bit decoder.
#include "../inc/dbc.h"
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define DBC_EXT_FLAG 0x80000000u
Functions
static void dbc_set_err (char *err, size_t errsz, const char *msg)
static void dbc_set_errno (char *err, size_t errsz, const char *prefix, const char *path)
static dbc_message_t * dbc_push_message (dbc_db_t *db)
Append an empty message slot to the database, growing as needed.
dbc_db_t * dbc_create_empty (const char *path)
Create an empty in-memory DBC database.
static dbc_message_t * parse_bo (const char *line, dbc_db_t *db)
Parse a BO_ message-definition line.
static int parse_sg (const char *line, dbc_message_t *m)
Parse a SG_ signal line and append it to the current message.
static dbc_message_t * find_message_by_raw_dbc_id (dbc_db_t *db, unsigned long raw_id)
static dbc_signal_t * find_signal_mut (dbc_message_t *m, const char *name)
static void unescape_dbc_string (char *dst, size_t dstsz, const char *src)
static void write_escaped_dbc_string (FILE *fp, const char *text)
static int parse_dbc_quoted_string (const char *p, char *dst, size_t dstsz)
static int parse_cm_sg (const char *line, dbc_db_t *db)
dbc_db_t * dbc_load_file (const char *path, char *err, size_t errsz)
Parse a DBC file into a new database.
void dbc_free (dbc_db_t *db)
Release a database returned by dbc_load_file.
const dbc_message_t * dbc_find_message (const dbc_db_t *db, uint32_t id, int is_extended)
Find the message definition matching a CAN identifier.
dbc_message_t * dbc_find_message_mut (dbc_db_t *db, uint32_t id, int is_extended)
Mutable variant of dbc_find_message.
dbc_message_t * dbc_upsert_message (dbc_db_t *db, uint32_t id, int is_extended, uint8_t dlc, const char *name, char *err, size_t errsz)
Add a message or update the metadata of an existing one.
int dbc_upsert_signal (dbc_db_t *db, dbc_message_t *msg, const dbc_signal_t *sig, int *replaced, char *err, size_t errsz)
Add or replace a signal in a message.
int dbc_save_file (const dbc_db_t *db, const char *path, char *err, size_t errsz)
Write a database to disk as a DBC file.
uint64_t dbc_extract_raw (const uint8_t *data, uint8_t dlc, const dbc_signal_t *sig)
Extract a signal's raw (unscaled) bit field from a payload.
double dbc_decode_physical (const dbc_signal_t *sig, uint64_t raw, int64_t *signed_raw_out)
Convert a raw field to its physical value.
Detailed Description
DBC (CAN database) parser and signal-bit decoder.
Implements dbc.h. The parser is a single-pass, line-oriented reader for the BO_ / SG_ records of the Vector DBC grammar plus signal comments. Anything it does not understand (value tables, attributes, node lists, …) is ignored, so it loads real-world databases without choking while extracting exactly the structure the Signal Analysis view needs.
The decoder handles both bit layouts:
Intel (little-endian): bits are consumed LSB-first, ascending.
Motorola (big-endian): bits are consumed MSB-first using the classic "sawtooth" traversal across the byte-wise LSB0 numbering.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file dbc.c.
Macro Definition Documentation
DBC_EXT_FLAG
#define DBC_EXT_FLAG 0x80000000u
Definition at line 31 of file dbc.c.
Function Documentation
dbc_set_err()
static void dbc_set_err (char * err, size_t errsz, const char * msg) static
Definition at line 33 of file dbc.c.
References n.
Referenced by dbc_save_file(), dbc_upsert_message(), and dbc_upsert_signal().
dbc_set_errno()
static void dbc_set_errno (char * err, size_t errsz, const char * prefix, const char * path) static
Definition at line 39 of file dbc.c.
References n.
Referenced by dbc_save_file().
dbc_push_message()
static dbc_message_t * dbc_push_message (dbc_db_t * db) static
Append an empty message slot to the database, growing as needed.
Parameters
db Database.
Returns
Pointer to the new (zeroed) message, or NULL on allocation failure.
Definition at line 55 of file dbc.c.
References n.
Referenced by dbc_upsert_message(), and parse_bo().
dbc_create_empty()
dbc_db_t * dbc_create_empty (const char * path)
Create an empty in-memory DBC database.
Parameters
path Optional path to remember as the database source.
Returns
A new empty database (free with dbc_free), or NULL.
Definition at line 70 of file dbc.c.
References n.
Referenced by on_save_signal(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
parse_bo()
static dbc_message_t * parse_bo (const char * line, dbc_db_t * db) static
Parse a BO_ message-definition line.
Parameters
line Line text (starting at "BO_").
db Database to append to.
Returns
Pointer to the new message (the current parse context), or NULL.
< Max message/signal name length.
Definition at line 86 of file dbc.c.
References DBC_EXT_FLAG, DBC_NAME_MAX, dbc_push_message(), and n.
Referenced by dbc_load_file().
parse_sg()
static int parse_sg (const char * line, dbc_message_t * m) static
Parse a SG_ signal line and append it to the current message.
Parameters
line Line text (leading whitespace already skipped, starts at "SG_").
m Current message (parse context).
Returns
0 on success, -1 on parse failure or when no message is open.
< Max signals stored per message.
< Max message/signal name length.
< Max signal unit string length.
Definition at line 118 of file dbc.c.
References DBC_MAX_SIGNALS_PER_MSG, DBC_NAME_MAX, DBC_UNIT_MAX, and n.
Referenced by dbc_load_file().
find_message_by_raw_dbc_id()
static dbc_message_t * find_message_by_raw_dbc_id (dbc_db_t * db, unsigned long raw_id) static
Definition at line 163 of file dbc.c.
References DBC_EXT_FLAG, dbc_find_message_mut(), and n.
Referenced by parse_cm_sg().
find_signal_mut()
static dbc_signal_t * find_signal_mut (dbc_message_t * m, const char * name) static
Definition at line 173 of file dbc.c.
References n.
Referenced by parse_cm_sg().
unescape_dbc_string()
static void unescape_dbc_string (char * dst, size_t dstsz, const char * src) static
Definition at line 183 of file dbc.c.
References n.
Referenced by parse_cm_sg().
write_escaped_dbc_string()
static void write_escaped_dbc_string (FILE * fp, const char * text) static
Definition at line 208 of file dbc.c.
References n.
Referenced by dbc_save_file().
parse_dbc_quoted_string()
static int parse_dbc_quoted_string (const char * p, char * dst, size_t dstsz) static
Definition at line 235 of file dbc.c.
References n.
Referenced by parse_cm_sg().
parse_cm_sg()
static int parse_cm_sg (const char * line, dbc_db_t * db) static
< Max message/signal name length.
< Max stored message/signal comment.
Definition at line 265 of file dbc.c.
References DBC_COMMENT_MAX, DBC_NAME_MAX, find_message_by_raw_dbc_id(), find_signal_mut(), n, parse_dbc_quoted_string(), sig, and unescape_dbc_string().
Referenced by dbc_load_file().
dbc_load_file()
dbc_db_t * dbc_load_file (const char * path, char * err, size_t errsz)
Parse a DBC file into a new database.
Parameters
path Path to the .dbc file.
err Optional buffer for a human-readable error (may be NULL).
errsz Size of err.
Returns
A new database (free with dbc_free), or NULL on failure.
Definition at line 313 of file dbc.c.
References dbc_free(), n, parse_bo(), parse_cm_sg(), and parse_sg().
Referenced by gui_signal_load_dbc(), on_save_signal(), selected_message_changed(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_free()
void dbc_free (dbc_db_t * db)
Release a database returned by dbc_load_file.
Parameters
db Database.
Definition at line 361 of file dbc.c.
References n.
Referenced by dbc_load_file(), gui_signal_clear_dbc(), gui_signal_load_dbc(), on_save_signal(), selected_message_changed(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_find_message()
const dbc_message_t * dbc_find_message (const dbc_db_t * db, uint32_t id, int is_extended)
Find the message definition matching a CAN identifier.
Parameters
db Database (may be NULL).
id Raw 11-/29-bit identifier.
is_extended Non-zero to match an extended-ID message.
Returns
The message, or NULL if not present.
Definition at line 369 of file dbc.c.
References n.
Referenced by gui_signal_decode_message(), selected_message_changed(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_find_message_mut()
dbc_message_t * dbc_find_message_mut (dbc_db_t * db, uint32_t id, int is_extended)
Mutable variant of dbc_find_message.
Parameters
db Database (may be NULL).
id Raw 11-/29-bit identifier.
is_extended Non-zero to match an extended-ID message.
Returns
The message, or NULL if not present.
Definition at line 382 of file dbc.c.
References n.
Referenced by dbc_upsert_message(), and find_message_by_raw_dbc_id().
dbc_upsert_message()
dbc_message_t * dbc_upsert_message (dbc_db_t * db, uint32_t id, int is_extended, uint8_t dlc, const char * name, char * err, size_t errsz)
Add a message or update the metadata of an existing one.
Parameters
db Database to modify.
id Raw 11-/29-bit identifier.
is_extended Non-zero for an extended-ID message.
dlc Declared payload length.
name Message name.
err Optional error buffer.
errsz Size of err.
Returns
The added/updated message, or NULL on failure.
Definition at line 395 of file dbc.c.
References dbc_find_message_mut(), dbc_push_message(), dbc_set_err(), and n.
Referenced by on_save_signal(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_upsert_signal()
int dbc_upsert_signal (dbc_db_t * db, dbc_message_t * msg, const dbc_signal_t * sig, int * replaced, char * err, size_t errsz)
Add or replace a signal in a message.
Parameters
db Database owning msg; used to maintain signal_count.
msg Message to modify.
sig Signal definition to copy in.
replaced Optional out: non-zero if an existing signal was replaced.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Max signals stored per message.
Definition at line 425 of file dbc.c.
References DBC_MAX_SIGNALS_PER_MSG, dbc_set_err(), n, and sig.
Referenced by on_save_signal(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_save_file()
int dbc_save_file (const dbc_db_t * db, const char * path, char * err, size_t errsz)
Write a database to disk as a DBC file.
Parameters
db Database to serialise.
path Destination path.
err Optional error buffer.
errsz Size of err.
Returns
0 on success, -1 on failure.
< Max signal unit string length.
Definition at line 463 of file dbc.c.
References DBC_EXT_FLAG, dbc_set_err(), dbc_set_errno(), DBC_UNIT_MAX, dbc_message_t::id, n, dbc_signal_t::unit, and write_escaped_dbc_string().
Referenced by on_save_signal(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_extract_raw()
uint64_t dbc_extract_raw (const uint8_t * data, uint8_t dlc, const dbc_signal_t * sig)
Extract a signal's raw (unscaled) bit field from a payload.
Parameters
data Payload bytes.
dlc Payload length in bytes.
sig Signal description.
Returns
The raw value, right-aligned (not sign-extended).
Definition at line 557 of file dbc.c.
References n, sig, and value.
Referenced by gui_db_creation_handle_message(), gui_signal_decode_message(), update_sample_preview(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().
dbc_decode_physical()
double dbc_decode_physical (const dbc_signal_t * sig, uint64_t raw, int64_t * signed_raw_out)
Convert a raw field to its physical value.
Parameters
sig Signal description.
raw Raw value from dbc_extract_raw.
signed_raw_out Optional out: sign-extended raw as a signed integer.
Returns
The physical value (raw * factor + offset).
Definition at line 593 of file dbc.c.
References n, and sig.
Referenced by gui_db_creation_handle_message(), gui_signal_decode_message(), update_sample_preview(), validate_candidate_dbc(), and validate_candidate_dbc_roundtrip().