CANoScope: inc/gui.h File Reference
gui.h File Reference
GTK GUI widget registry and the application's GUI/thread API.
#include <stddef.h>
#include <gtk/gtk.h>
#include "can_message.h"
#include "app_state.h"
#include "dbc.h"
Data Structures
struct gui_trace_rx_message_t
Snapshot of one RX row from the main trace table.
struct gui_widgets_t
Bundle of long-lived widgets, populated by gui_create_main_window.
Macros
#define GUI_TRACE_ID_TEXT_MAX 16
#define GUI_TRACE_DATA_TEXT_MAX 512
Enumerations
enum {
TCOL_SEQ = 0 , TCOL_DIR , TCOL_TIME , TCOL_ID ,
TCOL_TYPE , TCOL_DLC , TCOL_DATA , TCOL_INTERVAL ,
TCOL_FREQ , TCOL_COUNT , TCOL_FG , TCOL_ID_RAW ,
TCOL_EXT_RAW , TCOL_DIR_RAW , TCOL_DATA_RAW , TCOL_TS_NS ,
TCOL_NUM
}
Column indices of the trace GtkListStore.
Functions
GtkWidget * gui_create_main_window (GtkApplication *app)
Build the main application window and all of its widgets.
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
void gui_add_message (const can_msg_t *msg)
Append (or roll up) one frame into the trace view.
void gui_clear_trace (void)
Remove every row from the trace view.
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
size_t gui_trace_collect_rx_messages (gui_trace_rx_message_t *out, size_t max)
Collect current RX rows from the Receive/Transmit trace.
GtkWidget * gui_create_bit_analysis_view (void)
Build the Bit Analysis tab for CAN reverse engineering.
void gui_bit_analysis_handle_message (const can_msg_t *msg)
Feed one CAN frame to the Bit Analysis tab.
void gui_bit_analysis_reset (void)
Reset the current Bit Analysis session.
void gui_bit_analysis_trace_changed (void)
Notify Bit Analysis that trace contents changed.
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
gboolean gui_signal_load_dbc (const char *path)
Load (or replace) the active CAN database for signal decoding.
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
void gui_signal_decode_message (const can_msg_t *msg)
Decode one frame against the active database and update the signal rows.
const char * gui_signal_get_dbc_path (void)
Return the active DBC path used by Signal Analysis, or NULL.
GtkWidget * gui_create_db_creation_view (void)
Build the DB Creation tab for creating/updating DBC files from RX rows.
void gui_db_creation_trace_changed (void)
Notify the DB Creation tab that the trace RX list may have changed.
void gui_db_creation_handle_message (const can_msg_t *msg)
Feed one received frame to the DB Creation live preview graph.
void gui_db_creation_prefill_signal (uint32_t message_id, int is_extended, uint8_t dlc, const char *signal_name, uint16_t start_bit, uint8_t bit_length, int byte_order, int is_signed, double factor, double offset, double minimum, double maximum, const char *unit, const char *comment)
Pre-fill DB Creation from a Bit Analysis candidate.
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
void gui_plot_set_database (const dbc_db_t *db)
Rebuild the plot's series list from a database (or clear it).
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
GtkWidget * gui_create_math_view (void)
Build the Math tab for realtime two-signal analysis.
void gui_math_set_database (const dbc_db_t *db)
Rebuild the Math tab signal lists from a database.
void gui_math_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Feed one decoded signal value to the Math tab.
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
void gui_status_message (const char *fmt,...)
Set the status-bar text (printf-style).
void gui_show_settings_dialog (GtkWidget *parent)
Show the connection-settings dialog.
void gui_show_transmit_window (void)
Show the advanced transmit window.
void gui_show_about_dialog (GtkWidget *parent)
Show the About dialog (Taksys branding).
void gui_show_error (GtkWidget *parent, const char *title, const char *msg)
Show a modal error dialog.
void gui_format_id (char *buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
void gui_format_data (char *buf, size_t sz, const uint8_t *d, uint8_t dlc)
Format payload bytes into buf per the active data format.
const char * gui_msg_type_str (const can_msg_t *m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
void * thread_rx (void *arg)
Receive-thread entry point.
void * thread_tx (void *arg)
Transmit-thread entry point.
void * thread_stats (void *arg)
Statistics-thread entry point.
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Variables
gui_widgets_t g_gui
The process-wide GUI widget registry (defined in threads.c).
Detailed Description
GTK GUI widget registry and the application's GUI/thread API.
Declares the trace-view column layout, the global widget bundle (gui_widgets_t / g_gui), and every public function implemented by the gui/ sources: window construction, trace/statistics updates, dialogs, value formatting, the RX/TX/stats thread entry points, and the connect/disconnect lifecycle helpers.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file gui.h.
Macro Definition Documentation
GUI_TRACE_ID_TEXT_MAX
#define GUI_TRACE_ID_TEXT_MAX 16
Definition at line 51 of file gui.h.
GUI_TRACE_DATA_TEXT_MAX
#define GUI_TRACE_DATA_TEXT_MAX 512
Definition at line 52 of file gui.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indices of the trace GtkListStore.
Columns up to TCOL_COUNT are visible; the remainder are hidden helper columns used for sorting, row roll-up, and re-formatting.
Enumerator
TCOL_SEQ
Sequence number.
TCOL_DIR
Direction ("Rx"/"Tx").
TCOL_TIME
Formatted timestamp.
TCOL_ID
Formatted CAN identifier.
TCOL_TYPE
Frame type string.
TCOL_DLC
Data length code.
TCOL_DATA
Formatted payload.
TCOL_INTERVAL
Inter-frame interval (ms).
TCOL_FREQ
Frame frequency (Hz).
TCOL_COUNT
Hit count for rolled-up rows.
TCOL_FG
Row foreground colour (markup).
TCOL_ID_RAW
Hidden numeric ID for sorting / reformatting.
TCOL_EXT_RAW
Hidden extended-ID flag.
TCOL_DIR_RAW
Hidden direction flag for row roll-up.
TCOL_DATA_RAW
Hidden compact hex data for reformatting.
TCOL_TS_NS
Hidden last timestamp in nanoseconds.
TCOL_NUM
Number of columns (model width).
Definition at line 31 of file gui.h.
Function Documentation
gui_create_main_window()
GtkWidget * gui_create_main_window (GtkApplication * app)
Build the main application window and all of its widgets.
Parameters
app The owning GtkApplication.
Returns
The newly created top-level window.
Definition at line 1445 of file main_window.c.
References build_menubar(), build_stats_bar(), build_toolbar(), create_trace_view(), create_transmit_panel(), gui_widgets_t::db_creation_page, g_gui, gui_create_bit_analysis_view(), gui_create_db_creation_view(), gui_create_math_view(), gui_create_signal_plot(), gui_create_signal_view(), gui_load_logo(), gui_signal_load_default_dbc(), gui_update_stats(), gui_widgets_t::main_notebook, n, on_key_press(), on_window_delete(), gui_widgets_t::statusbar, gui_widgets_t::statusbar_ctx, and gui_widgets_t::window.
Referenced by on_app_activate().
gui_tx_panel_update_fd()
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
Widens each row's DLC range to 64 in CAN FD mode (8 in classic) and refreshes the number of visible data-byte fields.
< Maximum payload of a CAN FD frame.
< Maximum payload of a classic CAN frame.
Definition at line 1424 of file main_window.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, tx_panel_row_t::dlc_spin, app_state_t::fd_mode, g_app, n, s_txp, and txp_update_data_fields().
Referenced by app_do_connect(), and create_transmit_panel().
gui_add_message()
void gui_add_message (const can_msg_t * msg)
Append (or roll up) one frame into the trace view.
Parameters
msg Frame.
< Frame direction: received.
< Maximum payload of a CAN FD frame.
< Frame direction: received.
< Maximum payload of a CAN FD frame.
< Frame direction: transmitted.
< Frame direction: received.
Definition at line 383 of file message_view.c.
References CAN_DIR_RX, CAN_DIR_TX, DATA_TEXT_MAX, format_frequency(), format_interval(), format_raw_data(), format_timestamp(), FREQ_TEXT_MAX, g_gui, gui_bit_analysis_handle_message(), gui_db_creation_handle_message(), gui_db_creation_trace_changed(), gui_format_data(), gui_format_id(), gui_msg_type_str(), gui_signal_decode_message(), ID_TEXT_MAX, INTERVAL_TEXT_MAX, MAX_TRACE_ROWS, n, RAW_DATA_MAX, row_fg(), should_rollup_message(), TCOL_COUNT, TCOL_DATA, TCOL_DATA_RAW, TCOL_DIR, TCOL_DIR_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_FG, TCOL_FREQ, TCOL_ID, TCOL_ID_RAW, TCOL_INTERVAL, TCOL_SEQ, TCOL_TIME, TCOL_TS_NS, TCOL_TYPE, TIME_TEXT_MAX, timespec_to_ns(), gui_widgets_t::trace_row_seq, gui_widgets_t::trace_store, and gui_widgets_t::trace_view.
Referenced by idle_add_message().
gui_clear_trace()
void gui_clear_trace (void)
Remove every row from the trace view.
Definition at line 535 of file message_view.c.
References g_gui, gui_db_creation_trace_changed(), n, gui_widgets_t::trace_row_seq, and gui_widgets_t::trace_store.
Referenced by on_clear(), and on_dedup_toggle().
gui_refresh_trace_display()
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 544 of file message_view.c.
References CANFD_DATA_MAX, DATA_TEXT_MAX, g_gui, gui_format_data(), gui_format_id(), ID_TEXT_MAX, n, parse_raw_data(), TCOL_DATA, TCOL_DATA_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_ID, TCOL_ID_RAW, and gui_widgets_t::trace_store.
Referenced by on_data_format_toggle(), and on_id_format_toggle().
gui_trace_collect_rx_messages()
size_t gui_trace_collect_rx_messages (gui_trace_rx_message_t * out, size_t max)
Collect current RX rows from the Receive/Transmit trace.
Parameters
out Optional output array. Pass NULL to count only.
max Capacity of out.
Returns
Total RX rows available, even when greater than max.
< Frame direction: received.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 586 of file message_view.c.
References CAN_DIR_RX, CANFD_DATA_MAX, count, g_gui, n, parse_raw_data(), TCOL_COUNT, TCOL_DATA, TCOL_DATA_RAW, TCOL_DIR_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_ID, TCOL_ID_RAW, and gui_widgets_t::trace_store.
Referenced by db_creation_refresh_messages().
gui_create_bit_analysis_view()
GtkWidget * gui_create_bit_analysis_view (void)
Build the Bit Analysis tab for CAN reverse engineering.
Returns
A container widget for use as a notebook page.
Definition at line 1668 of file bit_analysis_view.c.
References bit_ui_t::accept_varying_check, add_text_column(), BA_DEFAULT_CAPACITY, BA_INPUT_CONTINUOUS, BA_SEGMENT_EVENT, BA_SEGMENT_STEP, ba_segment_type_name(), ba_session_init(), BA_UNIT_MAX, BA_VIEW_LIVE, bit_ui_t::bit_stats_label, CAND_COL_CHECKSUM, CAND_COL_CONF, CAND_COL_COUNTER, CAND_COL_DBC_START, CAND_COL_FACTOR, CAND_COL_LAG, CAND_COL_LEN, CAND_COL_MAE, CAND_COL_MUX, CAND_COL_MUX_BITS, CAND_COL_MUX_FRAMES, CAND_COL_MUX_RANGES, CAND_COL_MUX_VALUES, CAND_COL_NUM, CAND_COL_OFFSET, CAND_COL_ORDER, CAND_COL_PEARSON, CAND_COL_R2, CAND_COL_RANK, CAND_COL_SCORE, CAND_COL_SIGNED, CAND_COL_SPEARMAN, CAND_COL_START, CAND_COL_TIMESTAMP, CAND_COL_TRANSITIONS, CAND_COL_TS_RES, CAND_COL_VAL_MAE, CAND_COL_VAL_N, bit_ui_t::candidate_store, bit_ui_t::candidate_view, bit_ui_t::dir_combo, bit_ui_t::dlc_spin, ensure_refresh_timer(), bit_ui_t::fd_full_check, bit_ui_t::field_len_spin, bit_ui_t::field_order_combo, bit_ui_t::field_phys_label, bit_ui_t::field_raw_label, bit_ui_t::field_signed_check, bit_ui_t::field_start_spin, bit_ui_t::input_name_entry, bit_ui_t::input_type_combo, bit_ui_t::input_unit_entry, bit_ui_t::input_value_spin, bit_ui_t::inspector_label, make_tree(), bit_ui_t::matrix_area, bit_ui_t::mode_combo, n, on_add_marker_clicked(), on_analyze_clicked(), on_baseline_clicked(), on_candidate_selection_changed(), on_end_marker_clicked(), on_field_changed(), on_load_session_clicked(), on_mark_validated_clicked(), on_matrix_button(), on_matrix_draw(), on_pause_clicked(), on_promote_clicked(), on_reset_clicked(), on_save_session_clicked(), on_start_clicked(), on_target_changed(), on_timeline_draw(), refresh_bit_stats_label(), refresh_summary(), s_ba, ba_session_t::samples, SEG_COL_FRAMES, SEG_COL_LABEL, SEG_COL_NUM, SEG_COL_NUM_COLS, SEG_COL_TYPE, SEG_COL_VALUE, bit_ui_t::segment_label_entry, bit_ui_t::segment_store, bit_ui_t::segment_type_combo, bit_ui_t::segment_view, bit_ui_t::selected_bit, bit_ui_t::selected_candidate, bit_ui_t::session, sig, bit_ui_t::status_label, bit_ui_t::summary_label, SURV_COL_CHANGE_RATE, SURV_COL_CHANGED, SURV_COL_JITTER, SURV_COL_LABEL, SURV_COL_MEAN, SURV_COL_NUM, SURV_COL_UNIQUE, bit_ui_t::target_combo, bit_ui_t::target_store, and bit_ui_t::timeline_area.
Referenced by gui_create_main_window().
gui_bit_analysis_handle_message()
void gui_bit_analysis_handle_message (const can_msg_t * msg)
Feed one CAN frame to the Bit Analysis tab.
Parameters
msg Frame; ignored when it does not match the active target.
Definition at line 1632 of file bit_analysis_view.c.
References ba_session_t::active_segment, ba_session_push_frame(), bit_ui_t::dirty_view, n, s_ba, ba_segment_t::sample_count, ba_session_t::segment_count, ba_session_t::segments, bit_ui_t::session, and update_survey().
Referenced by gui_add_message().
gui_bit_analysis_reset()
void gui_bit_analysis_reset (void)
Reset the current Bit Analysis session.
Definition at line 1622 of file bit_analysis_view.c.
References n, and on_reset_clicked().
gui_bit_analysis_trace_changed()
void gui_bit_analysis_trace_changed (void)
Notify Bit Analysis that trace contents changed.
Definition at line 1627 of file bit_analysis_view.c.
References bit_ui_t::dirty_survey, n, and s_ba.
gui_create_signal_view()
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
Returns
A container widget for use as a notebook page.
Definition at line 320 of file signal_view.c.
References g_gui, gui_widgets_t::lbl_dbc, n, on_clear_dbc(), on_load_dbc(), on_reload_dbc(), SCOL_COUNT, SCOL_FG, SCOL_ID, SCOL_MSG, SCOL_NUM, SCOL_RANGE, SCOL_RAW, SCOL_SIGNAL, SCOL_UNIT, SCOL_VALUE, gui_widgets_t::sig_store, sig_update_dbc_label(), and gui_widgets_t::sig_view.
Referenced by gui_create_main_window().
gui_signal_load_dbc()
gboolean gui_signal_load_dbc (const char * path)
Load (or replace) the active CAN database for signal decoding.
Parameters
path Path to a .dbc file.
Returns
TRUE on success; on failure a status message is shown and the previous database (if any) is kept.
Definition at line 152 of file signal_view.c.
References dbc_free(), dbc_load_file(), gui_math_set_database(), gui_plot_set_database(), gui_status_message(), n, s_db, sig_table_rebuild(), and sig_update_dbc_label().
Referenced by gui_signal_load_default_dbc(), on_db_load(), on_load_dbc(), on_load_dbc(), on_reload_dbc(), and on_save_signal().
gui_signal_load_default_dbc()
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
Definition at line 190 of file signal_view.c.
References gui_find_asset(), gui_signal_load_dbc(), n, and sig_update_dbc_label().
Referenced by gui_create_main_window(), on_db_demo(), and on_reload_dbc().
gui_signal_clear_dbc()
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
Definition at line 177 of file signal_view.c.
References dbc_free(), gui_math_set_database(), gui_plot_set_database(), gui_status_message(), n, s_db, sig_table_rebuild(), and sig_update_dbc_label().
Referenced by on_clear_dbc(), and on_db_clear().
gui_signal_decode_message()
void gui_signal_decode_message (const can_msg_t * msg)
Decode one frame against the active database and update the signal rows.
Parameters
msg Frame (RX or TX); ignored when no database is loaded.
< Frame direction: transmitted.
Definition at line 208 of file signal_view.c.
References CAN_DIR_TX, dbc_decode_physical(), dbc_extract_raw(), dbc_find_message(), fmt_double(), g_gui, gui_math_add_sample(), gui_plot_add_sample(), n, s_db, SCOL_COUNT, SCOL_EXT, SCOL_FG, SCOL_MSGID, SCOL_RAW, SCOL_SIGIDX, SCOL_VALUE, and gui_widgets_t::sig_store.
Referenced by gui_add_message().
gui_signal_get_dbc_path()
const char * gui_signal_get_dbc_path (void)
Return the active DBC path used by Signal Analysis, or NULL.
Definition at line 199 of file signal_view.c.
References n, dbc_db_t::path, and s_db.
Referenced by gui_db_creation_prefill_signal(), and on_use_loaded_db().
gui_create_db_creation_view()
GtkWidget * gui_create_db_creation_view (void)
Build the DB Creation tab for creating/updating DBC files from RX rows.
Returns
A container widget for use as a notebook page.
< Max signal unit string length.
Definition at line 1051 of file db_creation.c.
References db_creation_refresh_messages(), DBC_UNIT_MAX, grid_label(), MCOL_LABEL, MCOL_NUM, n, new_double_spin(), on_graph_draw(), on_new_db(), on_open_db(), on_refresh_clicked(), on_save_signal(), on_use_loaded_db(), s_tab, selected_message_changed(), sig, and signal_form_changed().
Referenced by gui_create_main_window().
gui_db_creation_trace_changed()
void gui_db_creation_trace_changed (void)
Notify the DB Creation tab that the trace RX list may have changed.
Definition at line 588 of file db_creation.c.
References n, refresh_timer_cb(), and s_tab.
Referenced by gui_add_message(), and gui_clear_trace().
gui_db_creation_handle_message()
void gui_db_creation_handle_message (const can_msg_t * msg)
Feed one received frame to the DB Creation live preview graph.
Parameters
msg RX frame; ignored unless it matches the selected source message.
< Frame direction: received.
Definition at line 596 of file db_creation.c.
References CAN_DIR_RX, dbc_decode_physical(), dbc_extract_raw(), fmt_double(), get_selected_message(), graph_append(), gui_format_data(), gui_format_id(), GUI_TRACE_DATA_TEXT_MAX, GUI_TRACE_ID_TEXT_MAX, n, read_decode_signal(), s_tab, sig, and signal_fits_payload().
Referenced by gui_add_message().
gui_db_creation_prefill_signal()
void gui_db_creation_prefill_signal (uint32_t message_id, int is_extended, uint8_t dlc, const char * signal_name, uint16_t start_bit, uint8_t bit_length, int byte_order, int is_signed, double factor, double offset, double minimum, double maximum, const char * unit, const char * comment)
Pre-fill DB Creation from a Bit Analysis candidate.
Parameters
message_id Raw CAN identifier.
is_extended Non-zero for extended CAN ID.
dlc Message DLC.
signal_name Proposed signal name.
start_bit DBC start bit.
bit_length Signal bit length.
byte_order Non-zero for Intel/little-endian, zero for Motorola.
is_signed Non-zero for signed two's-complement.
factor DBC factor.
offset DBC offset.
minimum Physical minimum.
maximum Physical maximum.
unit Engineering unit.
comment Optional DBC signal comment/evidence.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Max message/signal name length.
Definition at line 641 of file db_creation.c.
References CANFD_DATA_MAX, gui_widgets_t::db_creation_page, db_creation_refresh_messages(), DBC_NAME_MAX, default_message_name(), g_gui, graph_clear(), gui_format_id(), gui_signal_get_dbc_path(), gui_status_message(), GUI_TRACE_DATA_TEXT_MAX, GUI_TRACE_ID_TEXT_MAX, label, gui_widgets_t::main_notebook, MCOL_DLC, MCOL_EXT, MCOL_ID, MCOL_LABEL, MCOL_RAW, n, s_tab, set_comment_text(), set_status(), and update_sample_preview().
Referenced by on_promote_clicked().
gui_create_signal_plot()
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Returns
A container widget for use as a notebook page.
Definition at line 931 of file signal_plot.c.
References n, on_add_window(), on_load_dbc(), on_tab_destroy(), s_count_lbl, and s_store.
Referenced by gui_create_main_window().
gui_plot_set_database()
void gui_plot_set_database (const dbc_db_t * db)
Rebuild the plot's series list from a database (or clear it).
Parameters
db Active database, or NULL to remove all series.
Definition at line 697 of file signal_plot.c.
References n, s_store, s_windows, win_populate_combo(), and win_remove_series().
Referenced by gui_signal_clear_dbc(), and gui_signal_load_dbc().
gui_plot_add_sample()
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
Parameters
id Raw CAN identifier.
is_ext Non-zero for an extended-ID message.
sig_idx Signal index within its message.
value Physical value.
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
Definition at line 165 of file signal_plot.c.
References n, plot_now(), PLOT_RING, s_store, store_find(), plot_signal_t::t, and value.
Referenced by gui_signal_decode_message().
gui_create_math_view()
GtkWidget * gui_create_math_view (void)
Build the Math tab for realtime two-signal analysis.
Returns
A container widget for use as a notebook page.
Definition at line 633 of file math_view.c.
References gui_math_set_database(), n, on_clear_clicked(), on_scatter_draw(), on_signal_changed(), on_time_draw(), on_window_changed(), and s_math.
Referenced by gui_create_main_window().
gui_math_set_database()
void gui_math_set_database (const dbc_db_t * db)
Rebuild the Math tab signal lists from a database.
Parameters
db Active database, or NULL to clear.
Definition at line 589 of file math_view.c.
References math_clear_samples(), n, s_math, and update_selected_indices().
Referenced by gui_create_math_view(), gui_signal_clear_dbc(), and gui_signal_load_dbc().
gui_math_add_sample()
void gui_math_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Feed one decoded signal value to the Math tab.
Parameters
id Raw CAN identifier.
is_ext Non-zero for extended-ID message.
sig_idx Signal index within its message.
value Decoded physical value.
Definition at line 560 of file math_view.c.
References append_pair(), n, refresh_all(), s_math, and value.
Referenced by gui_signal_decode_message().
gui_update_stats()
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
Definition at line 648 of file message_view.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, app_state_t::connected, app_state_t::error_count, g_app, g_gui, gui_bus_state_color(), gui_bus_state_str(), app_state_t::iface, gui_widgets_t::lbl_bitrate, gui_widgets_t::lbl_bus_load, gui_widgets_t::lbl_bus_state, gui_widgets_t::lbl_connection, gui_widgets_t::lbl_err, gui_widgets_t::lbl_rx, gui_widgets_t::lbl_stats_summary, gui_widgets_t::lbl_tx, n, gui_widgets_t::progress_bus_load, app_state_t::rx_count, and app_state_t::tx_count.
Referenced by app_do_disconnect(), gui_create_main_window(), and idle_update_stats().
gui_status_message()
void gui_status_message (const char * fmt, ...)
Set the status-bar text (printf-style).
Parameters
fmt printf format string.
... Format arguments.
Definition at line 718 of file message_view.c.
References g_gui, n, gui_widgets_t::statusbar, and gui_widgets_t::statusbar_ctx.
Referenced by app_do_connect(), app_do_disconnect(), gui_db_creation_prefill_signal(), gui_signal_clear_dbc(), gui_signal_load_dbc(), on_add_clicked(), on_clear(), on_data_format_toggle(), on_dedup_toggle(), on_id_format_toggle(), on_save_signal(), on_trace_save(), on_trace_start(), and on_trace_stop().
gui_show_settings_dialog()
void gui_show_settings_dialog (GtkWidget * parent)
Show the connection-settings dialog.
Parameters
parent Transient parent.
< Max interface-name length in app state.
Definition at line 170 of file settings_dialog.c.
References app_do_connect(), app_do_disconnect(), APP_MAX_IFACE_LEN, app_state_t::bitrate, app_state_t::connected, app_state_t::data_bitrate, app_state_t::fd_mode, app_state_t::filter_enabled, app_state_t::filter_ext, app_state_t::filter_id, app_state_t::filter_mask, g_app, GRID_LABEL, app_state_t::iface, label, app_state_t::listen_only, n, on_fd_toggled(), on_filter_toggled(), on_refresh_interfaces(), parse_bitrate(), populate_interfaces(), s_bitrates, s_fd_bitrates, and value.
Referenced by on_connect(), and on_settings().
gui_show_transmit_window()
void gui_show_transmit_window (void)
Show the advanced transmit window.
Definition at line 284 of file transmit_dialog.c.
References tx_win_t::brs_check, tx_win_t::cyclic_btn_start, tx_win_t::cyclic_btn_stop, tx_win_t::data_entry, tx_win_t::data_grid, tx_win_t::dlc_spin, tx_win_t::ext_check, tx_win_t::fd_check, FLABEL, g_gui, tx_win_t::id_entry, tx_win_t::interval_spin, MAX_DATA_ENTRIES, n, on_cyclic_start(), on_cyclic_stop(), on_dlc_changed(), on_fd_toggled(), on_rtr_toggled(), on_send_once(), on_tx_win_destroy(), tx_win_t::rtr_check, s_tx, tx_win_t::status_label, tx_win_t::window, and gui_widgets_t::window.
Referenced by on_transmit().
gui_show_about_dialog()
void gui_show_about_dialog (GtkWidget * parent)
Show the About dialog (Taksys branding).
Parameters
parent Transient parent.
Definition at line 1584 of file main_window.c.
References CANOSCOPE_APP_NAME, CANOSCOPE_COPYRIGHT, CANOSCOPE_VENDOR, CANOSCOPE_VERSION, gui_load_logo(), and n.
Referenced by on_about().
gui_show_error()
void gui_show_error (GtkWidget * parent, const char * title, const char * msg)
Show a modal error dialog.
Parameters
parent Transient parent (may be NULL).
title Window title.
msg Message body.
Definition at line 736 of file message_view.c.
References n.
Referenced by app_do_connect(), on_trace_save(), and on_trace_start().
gui_format_id()
void gui_format_id (char * buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
Parameters
buf Output buffer.
sz Buffer size.
id Identifier value.
is_ext Non-zero for an extended (29-bit) ID.
Definition at line 44 of file message_view.c.
References APP_ID_FORMAT_DEC, g_app, app_state_t::id_format, and n.
Referenced by format_target_label(), gui_add_message(), gui_db_creation_handle_message(), gui_db_creation_prefill_signal(), gui_refresh_trace_display(), and sig_table_rebuild().
gui_format_data()
void gui_format_data (char * buf, size_t sz, const uint8_t * d, uint8_t dlc)
Format payload bytes into buf per the active data format.
Parameters
buf Output buffer.
sz Buffer size.
d Payload bytes.
dlc Number of bytes.
Definition at line 57 of file message_view.c.
References APP_DATA_FORMAT_ASCII, APP_DATA_FORMAT_DEC, app_state_t::data_format, g_app, and n.
Referenced by gui_add_message(), gui_db_creation_handle_message(), gui_refresh_trace_display(), and refresh_target_store().
gui_msg_type_str()
const char * gui_msg_type_str (const can_msg_t * m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
Parameters
m Frame.
Returns
Static string.
Definition at line 197 of file message_view.c.
References n.
Referenced by gui_add_message(), and trace_csv_write_row().
gui_bus_state_str()
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 205 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, CAN_BUS_WARNING, and n.
Referenced by gui_update_stats().
gui_bus_state_color()
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 215 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, CAN_BUS_WARNING, and n.
Referenced by gui_update_stats().
thread_rx()
void * thread_rx (void * arg)
Receive-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: received.
Definition at line 163 of file threads.c.
References CAN_DIR_RX, DRV_CAN_OK, drv_can_recv(), app_state_t::error_count, g_app, idle_add_message(), app_state_t::msg_seq, n, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, and trace_record().
Referenced by app_do_connect().
thread_tx()
void * thread_tx (void * arg)
Transmit-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: transmitted.
Definition at line 204 of file threads.c.
References CAN_DIR_TX, DRV_CAN_OK, drv_can_send(), g_app, idle_update_stats(), app_state_t::msg_seq, n, trace_record(), app_state_t::tx_count, app_state_t::tx_queue, and app_state_t::tx_running.
Referenced by app_do_connect().
thread_stats()
void * thread_stats (void * arg)
Statistics-thread entry point.
Parameters
arg Unused.
Returns
NULL.
Definition at line 240 of file threads.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::connected, g_app, idle_update_stats(), n, app_state_t::period_bits, and app_state_t::stats_running.
Referenced by app_do_connect().
app_do_connect()
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
< Operation succeeded.
< Error-active bus state.
Definition at line 274 of file threads.c.
References app_state_t::bit_timing, app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, CAN_BUS_ACTIVE, app_state_t::connected, app_state_t::data_bitrate, drv_can_error_string(), drv_can_get_socketcan(), drv_can_init(), DRV_CAN_OK, drv_can_set_filter(), app_state_t::error_count, app_state_t::fd_mode, app_state_t::filter_enabled, app_state_t::filter_ext, app_state_t::filter_id, app_state_t::filter_mask, g_app, g_gui, gui_show_error(), gui_status_message(), gui_tx_panel_update_fd(), app_state_t::iface, app_state_t::listen_only, app_state_t::msg_seq, n, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::stats_running, app_state_t::stats_thread, thread_rx(), thread_stats(), thread_tx(), gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, app_state_t::tx_count, app_state_t::tx_running, app_state_t::tx_thread, and gui_widgets_t::window.
Referenced by gui_show_settings_dialog().
app_do_disconnect()
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Definition at line 344 of file threads.c.
References app_state_t::connected, drv_can_deinit(), g_app, g_gui, gui_status_message(), gui_update_stats(), app_state_t::iface, n, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::shutting_down, app_state_t::stats_running, app_state_t::stats_thread, gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, gui_widgets_t::toolbar_trace_start, gui_widgets_t::toolbar_trace_stop, app_state_t::tracing, app_state_t::tx_running, and app_state_t::tx_thread.
Referenced by app_state_cleanup(), gui_show_settings_dialog(), on_disconnect(), on_quit(), and on_window_delete().
Variable Documentation
g_gui
gui_widgets_t g_gui extern
The process-wide GUI widget registry (defined in threads.c).
The process-wide GUI widget registry (defined in threads.c).
Definition at line 38 of file threads.c.
Referenced by app_do_connect(), app_do_disconnect(), app_state_init(), build_stats_bar(), build_toolbar(), confirm_target_switch(), create_analysis_window(), create_stats_panel(), create_trace_view(), gui_add_message(), gui_clear_trace(), gui_create_main_window(), gui_create_signal_view(), gui_db_creation_prefill_signal(), gui_refresh_trace_display(), gui_show_transmit_window(), gui_signal_decode_message(), gui_status_message(), gui_trace_collect_rx_messages(), gui_update_stats(), idle_add_message(), idle_update_stats(), on_about(), on_connect(), on_db_load(), on_load_dbc(), on_load_dbc(), on_load_session_clicked(), on_new_db(), on_open_db(), on_quit(), on_settings(), on_trace_save(), on_trace_start(), on_trace_stop(), save_session_with_dialog(), sig_table_rebuild(), and sig_update_dbc_label().