CANoScope: gui/math_view.c File Reference
math_view.c File Reference
Realtime two-signal math analysis tab.
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/dbc.h"
Data Structures
struct math_signal_t
struct math_pair_t
struct math_stats_t
struct rank_item_t
Macros
#define MATH_MAX_SAMPLES 4096
Functions
static int sample_index (int logical)
static void math_clear_samples (void)
static int active_index (GtkWidget *combo)
static void update_selected_indices (void)
static void append_pair (double x, double y)
static double corr_for_lag (const double *x, const double *y, int n, int lag)
static int cmp_rank_item (const void *a, const void *b)
static void compute_ranks (const double *v, int n, double *rank)
static void collect_visible (double **x_out, double **y_out, double *tmin_out, double *tmax_out, int *n_out)
static math_stats_t compute_stats (const double *x, const double *y, int n)
static void update_stats_label (void)
static void draw_text (cairo_t *cr, const char *text, double x, double y)
static void draw_axes (cairo_t *cr, double x0, double y0, double x1, double y1)
static gboolean on_time_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
static gboolean on_scatter_draw (GtkWidget *widget, cairo_t *cr, gpointer data)
static void refresh_all (void)
static void on_signal_changed (GtkComboBox *combo, gpointer data)
static void on_clear_clicked (GtkWidget *button, gpointer data)
static void on_window_changed (GtkSpinButton *spin, gpointer data)
void gui_math_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Feed one decoded signal value to the Math tab.
void gui_math_set_database (const dbc_db_t *db)
Rebuild the Math tab signal lists from a database.
GtkWidget * gui_create_math_view (void)
Build the Math tab for realtime two-signal analysis.
Variables
struct {
math_signal_t * signals
int signal_count
GtkWidget * combo_x
GtkWidget * combo_y
GtkWidget * time_area
GtkWidget * scatter_area
GtkWidget * stats_label
GtkWidget * window_spin
math_pair_t samples [4096]
int head
int count
gint64 start_us
int x_idx
int y_idx
double last_x
double last_y
gboolean has_x
gboolean has_y
} s_math
Detailed Description
Realtime two-signal math analysis tab.
Definition in file math_view.c.
Macro Definition Documentation
MATH_MAX_SAMPLES
#define MATH_MAX_SAMPLES 4096
Definition at line 16 of file math_view.c.
Function Documentation
sample_index()
static int sample_index (int logical) static
Definition at line 78 of file math_view.c.
References MATH_MAX_SAMPLES, n, and s_math.
Referenced by collect_visible(), and on_time_draw().
math_clear_samples()
static void math_clear_samples (void) static
Definition at line 84 of file math_view.c.
References n, and s_math.
Referenced by gui_math_set_database(), on_clear_clicked(), and on_signal_changed().
active_index()
static int active_index (GtkWidget * combo) static
Definition at line 99 of file math_view.c.
References n, and s_math.
Referenced by update_selected_indices().
update_selected_indices()
static void update_selected_indices (void) static
Definition at line 107 of file math_view.c.
References active_index(), and s_math.
Referenced by gui_math_set_database(), and on_signal_changed().
append_pair()
static void append_pair (double x, double y) static
Definition at line 113 of file math_view.c.
References MATH_MAX_SAMPLES, n, and s_math.
Referenced by gui_math_add_sample().
corr_for_lag()
static double corr_for_lag (const double * x, const double * y, int n, int lag) static
Definition at line 128 of file math_view.c.
References n.
Referenced by compute_stats().
cmp_rank_item()
static int cmp_rank_item (const void * a, const void * b) static
Definition at line 157 of file math_view.c.
References n.
Referenced by compute_ranks().
compute_ranks()
static void compute_ranks (const double * v, int n, double * rank) static
Definition at line 164 of file math_view.c.
References cmp_rank_item(), and n.
Referenced by compute_stats().
collect_visible()
static void collect_visible (double ** x_out, double ** y_out, double * tmin_out, double * tmax_out, int * n_out) static
Definition at line 186 of file math_view.c.
References n, s_math, sample_index(), and math_pair_t::x.
Referenced by on_scatter_draw(), on_time_draw(), and update_stats_label().
compute_stats()
static math_stats_t compute_stats (const double * x, const double * y, int n) static
Definition at line 231 of file math_view.c.
References compute_ranks(), corr_for_lag(), and n.
Referenced by on_scatter_draw(), and update_stats_label().
update_stats_label()
static void update_stats_label (void) static
Definition at line 310 of file math_view.c.
References collect_visible(), compute_stats(), n, and s_math.
Referenced by refresh_all().
draw_text()
static void draw_text (cairo_t * cr, const char * text, double x, double y) static
Definition at line 345 of file math_view.c.
References n.
Referenced by on_scatter_draw(), and on_time_draw().
draw_axes()
static void draw_axes (cairo_t * cr, double x0, double y0, double x1, double y1) static
Definition at line 351 of file math_view.c.
References n.
Referenced by on_scatter_draw(), and on_time_draw().
on_time_draw()
static gboolean on_time_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Definition at line 371 of file math_view.c.
References collect_visible(), draw_axes(), draw_text(), label, n, s_math, and sample_index().
Referenced by gui_create_math_view().
on_scatter_draw()
static gboolean on_scatter_draw (GtkWidget * widget, cairo_t * cr, gpointer data) static
Definition at line 453 of file math_view.c.
References collect_visible(), compute_stats(), draw_axes(), draw_text(), label, and n.
Referenced by gui_create_math_view().
refresh_all()
static void refresh_all (void) static
Definition at line 529 of file math_view.c.
References n, s_math, and update_stats_label().
Referenced by gui_math_add_sample(), and on_window_changed().
on_signal_changed()
static void on_signal_changed (GtkComboBox * combo, gpointer data) static
Definition at line 538 of file math_view.c.
References math_clear_samples(), n, and update_selected_indices().
Referenced by gui_create_math_view().
on_clear_clicked()
static void on_clear_clicked (GtkWidget * button, gpointer data) static
Definition at line 546 of file math_view.c.
References math_clear_samples(), and n.
Referenced by gui_create_math_view().
on_window_changed()
static void on_window_changed (GtkSpinButton * spin, gpointer data) static
Definition at line 553 of file math_view.c.
References n, and refresh_all().
Referenced by gui_create_math_view().
gui_math_add_sample()
void gui_math_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Feed one decoded signal value to the Math tab.
Parameters
id Raw CAN identifier.
is_ext Non-zero for extended-ID message.
sig_idx Signal index within its message.
value Decoded physical value.
Definition at line 560 of file math_view.c.
References append_pair(), n, refresh_all(), s_math, and value.
Referenced by gui_signal_decode_message().
gui_math_set_database()
void gui_math_set_database (const dbc_db_t * db)
Rebuild the Math tab signal lists from a database.
Parameters
db Active database, or NULL to clear.
Definition at line 589 of file math_view.c.
References math_clear_samples(), n, s_math, and update_selected_indices().
Referenced by gui_create_math_view(), gui_signal_clear_dbc(), and gui_signal_load_dbc().
gui_create_math_view()
GtkWidget * gui_create_math_view (void)
Build the Math tab for realtime two-signal analysis.
Returns
A container widget for use as a notebook page.
Definition at line 633 of file math_view.c.
References gui_math_set_database(), n, on_clear_clicked(), on_scatter_draw(), on_signal_changed(), on_time_draw(), on_window_changed(), and s_math.
Referenced by gui_create_main_window().
Variable Documentation
signals
math_signal_t* signals
Definition at line 50 of file math_view.c.
signal_count
int signal_count
Definition at line 51 of file math_view.c.
combo_x
GtkWidget* combo_x
Definition at line 53 of file math_view.c.
combo_y
GtkWidget* combo_y
Definition at line 54 of file math_view.c.
time_area
GtkWidget* time_area
Definition at line 55 of file math_view.c.
scatter_area
GtkWidget* scatter_area
Definition at line 56 of file math_view.c.
stats_label
GtkWidget* stats_label
Definition at line 57 of file math_view.c.
window_spin
GtkWidget* window_spin
Definition at line 58 of file math_view.c.
samples
math_pair_t samples[4096]
Definition at line 60 of file math_view.c.
Referenced by ba_session_analyze(), ba_session_reset(), collect_lagged_pairs(), compute_best_lag_ms(), compute_bit_stats(), estimate_lag_step_ns(), evaluate_candidate(), lagged_corr_for_values(), mux_score_for_values(), timestamp_score_for_values(), and transition_score_for_values().
head
int head
Definition at line 61 of file math_view.c.
count
int count
Definition at line 62 of file math_view.c.
start_us
gint64 start_us
Definition at line 63 of file math_view.c.
x_idx
int x_idx
Definition at line 65 of file math_view.c.
y_idx
int y_idx
Definition at line 66 of file math_view.c.
last_x
double last_x
Definition at line 67 of file math_view.c.
Referenced by on_graph_draw().
last_y
double last_y
Definition at line 68 of file math_view.c.
Referenced by on_graph_draw().
has_x
gboolean has_x
Definition at line 69 of file math_view.c.
has_y
gboolean has_y
Definition at line 70 of file math_view.c.
[struct]
struct { ... } s_math
Referenced by active_index(), append_pair(), collect_visible(), gui_create_math_view(), gui_math_add_sample(), gui_math_set_database(), math_clear_samples(), on_time_draw(), refresh_all(), sample_index(), update_selected_indices(), and update_stats_label().