CANoScope: gui/signal_plot.c File Reference
signal_plot.c File Reference
Signal Analysis Viewer — detachable multi-window signal-over-time graphs.
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/dbc.h"
Data Structures
struct plot_signal_t
One plottable signal with its rolling sample history.
struct win_series_t
One signal selected inside a window (references the store).
struct plot_window_t
One detached analysis window with its own graph + side legend.
Macros
#define PLOT_RING 30000
Samples kept per signal (~30 s @ 1 kHz).
#define PLOT_REDRAW_MS 33
Redraw period (~30 fps) while windows open.
#define PLOT_MAX_SERIES 64
Max signals plotted in one window.
#define PLOT_HOVER_PX 18.0
Cursor snap radius for hover tooltip (px).
#define PALETTE_N ((int)(sizeof(PALETTE) / sizeof(PALETTE[0])))
Functions
const char * gui_find_asset (const char *name)
Resolve a bundled asset path (defined in main_window.c).
static double plot_now (void)
Seconds elapsed since the store's monotonic origin.
static double win_now (const plot_window_t *pw)
The effective "now" for a window (frozen while paused).
static int store_find (uint32_t id, int ext, int sig_idx)
Locate a stored signal by message/signal identity, or -1.
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
static void win_populate_combo (plot_window_t *pw)
Forward declaration: rebuild a window's dropdown from the store.
static void win_remove_series (plot_window_t *pw, int s)
Remove series s from window pw and drop its legend row.
static void on_legend_remove (GtkWidget *btn, gpointer data)
"×" remove-button handler for a side-pane legend row.
static void win_add_series (plot_window_t *pw, int store_idx)
Add stored signal store_idx to window pw (idempotent).
static void win_refresh_legend (plot_window_t *pw)
Update every side-pane row's live value for window pw.
static double norm_to_y (double norm, double y0, double y1)
Map a normalised value (0..1) to a Y pixel within the plot rect.
static void series_scale (const plot_signal_t *sig, double tmin, double *base, double *span)
Compute a series' normalisation base/span (auto-scale fallback).
static gboolean on_draw (GtkWidget *w, cairo_t *cr, gpointer data)
Cairo draw handler for a window's graph (no legend; hover tooltip).
static gboolean on_motion (GtkWidget *w, GdkEventMotion *e, gpointer data)
Track the cursor for hover tooltips.
static gboolean on_leave (GtkWidget *w, GdkEventCrossing *e, gpointer data)
Drop the hover tooltip when the cursor leaves the plot.
static void on_add_clicked (GtkWidget *btn, gpointer data)
"Add" — add the dropdown's current signal to the window.
static void on_combo_activate (GtkEntry *entry, gpointer data)
Enter in the dropdown entry behaves like clicking "Add".
static void on_pause (GtkToggleButton *btn, gpointer data)
Per-window pause toggle.
static void on_window_changed (GtkSpinButton *btn, gpointer data)
Per-window time-window width spin.
static void on_clear_clicked (GtkWidget *btn, gpointer data)
"Clear" — remove every signal from this window.
static void update_count_label (void)
Refresh the tab-level "N analysis windows open" label.
static void on_window_destroy (GtkWidget *w, gpointer data)
A window was closed — unlink it from the global list and free.
void gui_plot_set_database (const dbc_db_t *db)
Rebuild the plot's series list from a database (or clear it).
static gboolean plot_tick (gpointer data)
Repaint every open window and refresh its side-pane values.
static void create_analysis_window (void)
Build and show one detached analysis window.
static void on_add_window (GtkWidget *w, gpointer d)
"Add Analysis Window" — open a new detached graph window.
static void on_load_dbc (GtkWidget *w, gpointer d)
"Load DBC…" — choose a database after launch (delegates).
static void on_tab_destroy (GtkWidget *w, gpointer d)
Free the redraw timer if the tab is destroyed (app shutdown).
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Variables
static const double PALETTE [][3]
Distinct trace colours (RGB 0..1), cycled across a window's series.
struct {
plot_signal_t * sig
Per-signal store (one per DBC signal).
int n
Number of stored signals.
gint64 start_us
Monotonic origin for sample times.
} s_store
static GList * s_windows
List of open plot_window_t analysis windows.
static guint s_timer
Shared ~30 fps redraw timer (runs while any window is open).
static GtkWidget * s_count_lbl
Tab-level label reporting the number of open analysis windows.
Detailed Description
Signal Analysis Viewer — detachable multi-window signal-over-time graphs.
Implements a Vector-CANalyzer "Graphics"-style analysis workspace. Instead of a single fixed graph, the Signal Analysis Viewer tab is a launcher: each Add Analysis Window click opens an independent, detached top-level window containing its own oscilloscope-style graph. Within a window the user adds signals through a searchable dropdown (type to filter, pick, Add); each selected signal is plotted with its own colour.
Decoding feeds a single central sample store: every decoded sample (delivered from the Signal Analysis decode path via gui_plot_add_sample) is appended to a per-signal ring buffer, independent of which windows exist. A freshly opened window therefore immediately shows the recent history, and several windows can plot the same signal without duplicating storage.
Each window renders with Cairo: signals are normalised to their DBC [min,max] range so disparate physical ranges share the vertical space, and every plotted signal draws its own colour-matched Y axis on the left with real physical-value tick labels and its engineering unit (rather than a single shared 0-100 % scale). The graph itself carries no overlaid legend — hovering the cursor over the plot snaps to the nearest sample and shows a tooltip with the signal name, its value/unit and the time, while a side pane lists the colour swatch, name and live value of every selected signal. A single redraw timer repaints all open windows at ~30 fps and refreshes their side-pane values.
All sample appends and draws happen on the GTK main thread (the decode path runs in a GLib idle callback), so no locking is required.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file signal_plot.c.
Macro Definition Documentation
PLOT_RING
#define PLOT_RING 30000
Samples kept per signal (~30 s @ 1 kHz).
Definition at line 47 of file signal_plot.c.
PLOT_REDRAW_MS
#define PLOT_REDRAW_MS 33
Redraw period (~30 fps) while windows open.
Definition at line 48 of file signal_plot.c.
PLOT_MAX_SERIES
#define PLOT_MAX_SERIES 64
Max signals plotted in one window.
Definition at line 49 of file signal_plot.c.
PLOT_HOVER_PX
#define PLOT_HOVER_PX 18.0
Cursor snap radius for hover tooltip (px).
Definition at line 50 of file signal_plot.c.
PALETTE_N
#define PALETTE_N ((int)(sizeof(PALETTE) / sizeof(PALETTE[0])))
Definition at line 62 of file signal_plot.c.
Function Documentation
gui_find_asset()
const char * gui_find_asset (const char * name) extern
Resolve a bundled asset path (defined in main_window.c).
Resolve a bundled asset path (defined in main_window.c).
Searches, in order: $CANOSCOPE_ASSET_DIR, paths relative to the executable (dev assets/ and installed ../share/canoscope), and the system share dirs.
Parameters
name Asset filename (e.g. "taksys_logo.png").
Returns
Static path string valid until the next call, or NULL if not found.
Definition at line 66 of file main_window.c.
plot_now()
static double plot_now (void) static
Seconds elapsed since the store's monotonic origin.
Definition at line 106 of file signal_plot.c.
References s_store.
Referenced by gui_plot_add_sample(), on_pause(), and win_now().
win_now()
static double win_now (const plot_window_t * pw) static
The effective "now" for a window (frozen while paused).
Definition at line 145 of file signal_plot.c.
References plot_window_t::frozen_now, plot_window_t::paused, and plot_now().
Referenced by on_draw().
store_find()
static int store_find (uint32_t id, int ext, int sig_idx) static
Locate a stored signal by message/signal identity, or -1.
Definition at line 155 of file signal_plot.c.
References plot_signal_t::ext, plot_signal_t::id, s_store, and plot_signal_t::sig_idx.
Referenced by gui_plot_add_sample().
gui_plot_add_sample()
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
Parameters
id Raw CAN identifier.
is_ext Non-zero for an extended-ID message.
sig_idx Signal index within its message.
value Physical value.
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
Definition at line 165 of file signal_plot.c.
References plot_signal_t::count, plot_signal_t::has_last, plot_signal_t::head, plot_signal_t::last, plot_now(), PLOT_RING, s_store, store_find(), plot_signal_t::t, plot_signal_t::v, and value.
Referenced by gui_signal_decode_message().
win_populate_combo()
static void win_populate_combo (plot_window_t * pw) static
Forward declaration: rebuild a window's dropdown from the store.
(Re)build a window's dropdown list from the current store.
Definition at line 685 of file signal_plot.c.
References plot_window_t::combo, and s_store.
Referenced by create_analysis_window(), and gui_plot_set_database().
win_remove_series()
static void win_remove_series (plot_window_t * pw, int s) static
Remove series s from window pw and drop its legend row.
Definition at line 191 of file signal_plot.c.
References plot_window_t::area, plot_window_t::n_series, win_series_t::row, and plot_window_t::series.
Referenced by gui_plot_set_database(), on_clear_clicked(), and on_legend_remove().
on_legend_remove()
static void on_legend_remove (GtkWidget * btn, gpointer data) static
"×" remove-button handler for a side-pane legend row.
Definition at line 205 of file signal_plot.c.
References plot_window_t::n_series, plot_window_t::series, win_series_t::sig, and win_remove_series().
Referenced by win_add_series().
win_add_series()
static void win_add_series (plot_window_t * pw, int store_idx) static
Add stored signal store_idx to window pw (idempotent).
< Max signals plotted in one window.
< Max message/signal name length.
Definition at line 220 of file signal_plot.c.
References plot_window_t::area, win_series_t::col, plot_window_t::color_next, DBC_NAME_MAX, plot_signal_t::label, plot_window_t::legend_box, plot_window_t::n_series, on_legend_remove(), PALETTE, PALETTE_N, PLOT_MAX_SERIES, win_series_t::row, s_store, plot_window_t::series, sig, win_series_t::sig, and win_series_t::val_label.
Referenced by on_add_clicked().
win_refresh_legend()
static void win_refresh_legend (plot_window_t * pw) static
Update every side-pane row's live value for window pw.
Definition at line 275 of file signal_plot.c.
References plot_signal_t::has_last, plot_signal_t::last, plot_window_t::n_series, s_store, plot_window_t::series, sig, win_series_t::sig, plot_signal_t::unit, and win_series_t::val_label.
Referenced by plot_tick().
norm_to_y()
static double norm_to_y (double norm, double y0, double y1) static
Map a normalised value (0..1) to a Y pixel within the plot rect.
Definition at line 293 of file signal_plot.c.
Referenced by on_draw().
series_scale()
static void series_scale (const plot_signal_t * sig, double tmin, double * base, double * span) static
Compute a series' normalisation base/span (auto-scale fallback).
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
Definition at line 301 of file signal_plot.c.
References plot_signal_t::count, plot_signal_t::dmax, plot_signal_t::dmin, plot_signal_t::head, PLOT_RING, sig, plot_signal_t::t, and plot_signal_t::v.
Referenced by on_draw().
on_draw()
static gboolean on_draw (GtkWidget * w, cairo_t * cr, gpointer data) static
Cairo draw handler for a window's graph (no legend; hover tooltip).
< Max signals plotted in one window.
< Max signals plotted in one window.
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
< Samples kept per signal (~30 s @ 1 kHz).
< Cursor snap radius for hover tooltip (px).
< Cursor snap radius for hover tooltip (px).
< Max message/signal name length.
Definition at line 324 of file signal_plot.c.
References win_series_t::col, plot_signal_t::count, DBC_NAME_MAX, plot_signal_t::head, plot_window_t::hover_on, plot_window_t::hover_x, plot_window_t::hover_y, plot_signal_t::label, plot_window_t::n_series, norm_to_y(), PLOT_HOVER_PX, PLOT_MAX_SERIES, PLOT_RING, s_store, plot_window_t::series, series_scale(), sig, win_series_t::sig, plot_signal_t::t, plot_signal_t::unit, plot_signal_t::v, win_now(), and plot_window_t::window_sec.
Referenced by create_analysis_window().
on_motion()
static gboolean on_motion (GtkWidget * w, GdkEventMotion * e, gpointer data) static
Track the cursor for hover tooltips.
Definition at line 578 of file signal_plot.c.
References plot_window_t::hover_on, plot_window_t::hover_x, and plot_window_t::hover_y.
Referenced by create_analysis_window().
on_leave()
static gboolean on_leave (GtkWidget * w, GdkEventCrossing * e, gpointer data) static
Drop the hover tooltip when the cursor leaves the plot.
Definition at line 589 of file signal_plot.c.
References plot_window_t::hover_on.
Referenced by create_analysis_window().
on_add_clicked()
static void on_add_clicked (GtkWidget * btn, gpointer data) static
"Add" — add the dropdown's current signal to the window.
Definition at line 599 of file signal_plot.c.
References plot_window_t::combo, gui_status_message(), s_store, and win_add_series().
Referenced by create_analysis_window(), and on_combo_activate().
on_combo_activate()
static void on_combo_activate (GtkEntry * entry, gpointer data) static
Enter in the dropdown entry behaves like clicking "Add".
Definition at line 618 of file signal_plot.c.
References on_add_clicked().
Referenced by create_analysis_window().
on_pause()
static void on_pause (GtkToggleButton * btn, gpointer data) static
Per-window pause toggle.
Definition at line 625 of file signal_plot.c.
References plot_window_t::area, plot_window_t::frozen_now, plot_window_t::paused, and plot_now().
Referenced by create_analysis_window().
on_window_changed()
static void on_window_changed (GtkSpinButton * btn, gpointer data) static
Per-window time-window width spin.
Definition at line 636 of file signal_plot.c.
References plot_window_t::area, and plot_window_t::window_sec.
Referenced by create_analysis_window().
on_clear_clicked()
static void on_clear_clicked (GtkWidget * btn, gpointer data) static
"Clear" — remove every signal from this window.
Definition at line 645 of file signal_plot.c.
References plot_window_t::color_next, plot_window_t::n_series, and win_remove_series().
Referenced by create_analysis_window().
update_count_label()
static void update_count_label (void) static
Refresh the tab-level "N analysis windows open" label.
Definition at line 655 of file signal_plot.c.
References n, s_count_lbl, and s_windows.
Referenced by create_analysis_window(), and on_window_destroy().
on_window_destroy()
static void on_window_destroy (GtkWidget * w, gpointer data) static
A window was closed — unlink it from the global list and free.
Definition at line 667 of file signal_plot.c.
References s_timer, s_windows, and update_count_label().
Referenced by create_analysis_window().
gui_plot_set_database()
void gui_plot_set_database (const dbc_db_t * db)
Rebuild the plot's series list from a database (or clear it).
Parameters
db Active database, or NULL to remove all series.
Definition at line 697 of file signal_plot.c.
References plot_window_t::area, plot_window_t::color_next, plot_signal_t::dmax, plot_signal_t::dmin, plot_signal_t::ext, plot_signal_t::id, dbc_message_t::id, dbc_message_t::is_extended, plot_signal_t::label, dbc_signal_t::max, dbc_db_t::message_count, dbc_db_t::messages, dbc_signal_t::min, n, plot_window_t::n_series, dbc_signal_t::name, dbc_message_t::name, s_store, s_windows, plot_signal_t::sig_idx, dbc_message_t::signal_count, dbc_db_t::signal_count, dbc_message_t::signals, plot_signal_t::unit, dbc_signal_t::unit, win_populate_combo(), and win_remove_series().
Referenced by gui_signal_clear_dbc(), and gui_signal_load_dbc().
plot_tick()
static gboolean plot_tick (gpointer data) static
Repaint every open window and refresh its side-pane values.
Definition at line 744 of file signal_plot.c.
References plot_window_t::area, s_windows, and win_refresh_legend().
Referenced by create_analysis_window().
create_analysis_window()
static void create_analysis_window (void) static
Build and show one detached analysis window.
< Redraw period (~30 fps) while windows open.
Definition at line 761 of file signal_plot.c.
References plot_window_t::area, plot_window_t::combo, g_gui, plot_window_t::idx, plot_window_t::legend_box, on_add_clicked(), on_clear_clicked(), on_combo_activate(), on_draw(), on_leave(), on_motion(), on_pause(), on_window_changed(), on_window_destroy(), PLOT_REDRAW_MS, plot_tick(), s_timer, s_windows, update_count_label(), plot_window_t::win, win_populate_combo(), gui_widgets_t::window, and plot_window_t::window_sec.
Referenced by on_add_window().
on_add_window()
static void on_add_window (GtkWidget * w, gpointer d) static
"Add Analysis Window" — open a new detached graph window.
Definition at line 890 of file signal_plot.c.
References create_analysis_window().
Referenced by gui_create_signal_plot().
on_load_dbc()
static void on_load_dbc (GtkWidget * w, gpointer d) static
"Load DBC…" — choose a database after launch (delegates).
Definition at line 897 of file signal_plot.c.
References g_gui, gui_signal_load_dbc(), and gui_widgets_t::window.
Referenced by gui_create_signal_plot().
on_tab_destroy()
static void on_tab_destroy (GtkWidget * w, gpointer d) static
Free the redraw timer if the tab is destroyed (app shutdown).
Definition at line 922 of file signal_plot.c.
References s_timer.
Referenced by gui_create_signal_plot().
gui_create_signal_plot()
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Returns
A container widget for use as a notebook page.
Definition at line 931 of file signal_plot.c.
References on_add_window(), on_load_dbc(), on_tab_destroy(), s_count_lbl, and s_store.
Referenced by gui_create_main_window().
Variable Documentation
PALETTE
const double PALETTE[][3] static
Initial value:
= {
    { 0.20, 0.60, 0.86 }, { 0.91, 0.30, 0.24 }, { 0.18, 0.80, 0.44 },
    { 0.95, 0.61, 0.07 }, { 0.61, 0.35, 0.71 }, { 0.10, 0.74, 0.61 },
    { 0.90, 0.49, 0.13 }, { 0.52, 0.58, 0.59 }, { 0.83, 0.33, 0.64 },
    { 0.16, 0.50, 0.73 }, { 0.86, 0.78, 0.13 }, { 0.40, 0.76, 0.65 },
}
Distinct trace colours (RGB 0..1), cycled across a window's series.
Definition at line 56 of file signal_plot.c.
Referenced by win_add_series().
sig
plot_signal_t* sig
Per-signal store (one per DBC signal).
Definition at line 91 of file signal_plot.c.
Referenced by dbc_decode_physical(), dbc_extract_raw(), on_draw(), series_scale(), win_add_series(), and win_refresh_legend().
n
int n
Number of stored signals.
Definition at line 92 of file signal_plot.c.
Referenced by canfd_round_len(), gui_add_message(), gui_find_asset(), gui_plot_set_database(), iface_is_up(), on_trace_save(), parse_bo(), populate_interfaces(), run_ip_priv(), socketcan_list_interfaces(), socketcan_recv(), socketcan_send(), and update_count_label().
start_us
gint64 start_us
Monotonic origin for sample times.
Definition at line 93 of file signal_plot.c.
[struct]
struct { ... } s_store
Referenced by gui_create_signal_plot(), gui_plot_add_sample(), gui_plot_set_database(), on_add_clicked(), on_draw(), plot_now(), store_find(), win_add_series(), win_populate_combo(), and win_refresh_legend().
s_windows
GList* s_windows static
List of open plot_window_t analysis windows.
Definition at line 97 of file signal_plot.c.
Referenced by create_analysis_window(), gui_plot_set_database(), on_window_destroy(), plot_tick(), and update_count_label().
s_timer
guint s_timer static
Shared ~30 fps redraw timer (runs while any window is open).
Definition at line 100 of file signal_plot.c.
Referenced by create_analysis_window(), on_tab_destroy(), and on_window_destroy().
s_count_lbl
GtkWidget* s_count_lbl static
Tab-level label reporting the number of open analysis windows.
Definition at line 103 of file signal_plot.c.
Referenced by gui_create_signal_plot(), and update_count_label().