CANoScope: tests/test_bit_analysis.c File Reference
test_bit_analysis.c File Reference
Focused regression tests for the Bit Analysis engine and DBC promotion.
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "../inc/bit_analysis.h"
#include "../inc/dbc.h"
Functions
static void check (int condition, const char *message)
static void put_u64_le (uint8_t out[64], uint64_t v)
static void put_motorola (uint8_t out[64], uint16_t dbc_start_bit, uint8_t bit_length, uint64_t value)
static void put_candidate_raw (uint8_t out[64], const ba_candidate_t *candidate, uint64_t value)
static can_msg_t make_msg (uint32_t id, int is_extended, uint8_t dlc, uint8_t direction, uint64_t seq)
static void extraction_tests (void)
static void target_filter_tests (void)
static void validate_candidate_dbc (const ba_candidate_t *candidate)
static void validate_candidate_dbc_roundtrip (const ba_candidate_t *candidate, uint32_t message_id, int is_extended, uint8_t dlc, const uint64_t *raw_values, size_t raw_count)
static void candidate_tests (void)
static void baseline_segment_tests (void)
static void validation_segment_tests (void)
static void transition_match_tests (void)
static void checksum_tests (void)
static void mux_tests (void)
static void timestamp_tests (void)
static void signed_candidate_tests (void)
static void motorola_candidate_tests (void)
static void lag_tests (void)
static void bit_lag_tests (void)
static double elapsed_seconds (const struct timespec *a, const struct timespec *b)
static void fast_path_tests (void)
int main (void)
Variables
static int failures
Detailed Description
Focused regression tests for the Bit Analysis engine and DBC promotion.
Builds a set of deterministic synthetic CAN traces that exercise bit extraction, target filtering, baseline capture, candidate scanning, signedness, Motorola conversion, lag detection, counter/checksum/timestamp heuristics, multiplexer evidence, validation segments, JSON persistence, and DBC round-trips. The test binary is intentionally separate from the GTK UI so it can run in CI and on development machines without CAN hardware.
Definition in file test_bit_analysis.c.
Function Documentation
check()
static void check (int condition, const char * message) static
Definition at line 26 of file test_bit_analysis.c.
References failures, and n.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), extraction_tests(), fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), validate_candidate_dbc(), validate_candidate_dbc_roundtrip(), and validation_segment_tests().
put_u64_le()
static void put_u64_le (uint8_t out[64/**< Maximum payload of a CAN FD frame. */], uint64_t v) static
< Maximum payload of a CAN FD frame.
Definition at line 34 of file test_bit_analysis.c.
References CANFD_DATA_MAX, and n.
Referenced by baseline_segment_tests(), bit_lag_tests(), candidate_tests(), fast_path_tests(), lag_tests(), mux_tests(), signed_candidate_tests(), timestamp_tests(), transition_match_tests(), validate_candidate_dbc(), and validation_segment_tests().
put_motorola()
static void put_motorola (uint8_t out[64/**< Maximum payload of a CAN FD frame. */], uint16_t dbc_start_bit, uint8_t bit_length, uint64_t value) static
< Maximum payload of a CAN FD frame.
Definition at line 41 of file test_bit_analysis.c.
References CANFD_DATA_MAX, n, and value.
Referenced by motorola_candidate_tests(), and put_candidate_raw().
put_candidate_raw()
static void put_candidate_raw (uint8_t out[64/**< Maximum payload of a CAN FD frame. */], const ba_candidate_t * candidate, uint64_t value) static
< Maximum payload of a CAN FD frame.
Definition at line 58 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, CANFD_DATA_MAX, n, put_motorola(), and value.
Referenced by validate_candidate_dbc_roundtrip().
make_msg()
static can_msg_t make_msg (uint32_t id, int is_extended, uint8_t dlc, uint8_t direction, uint64_t seq) static
< Maximum payload of a CAN FD frame.
Definition at line 78 of file test_bit_analysis.c.
References CANFD_DATA_MAX, and n.
Referenced by target_filter_tests().
extraction_tests()
static void extraction_tests (void) static
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 98 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, BA_BYTE_ORDER_MOTOROLA, ba_canonical_to_dbc_start_bit(), ba_dbc_to_canonical_start_bit(), ba_extract_unsigned(), ba_sign_extend(), CANFD_DATA_MAX, check(), and n.
Referenced by main().
target_filter_tests()
static void target_filter_tests (void) static
< Frame direction: received.
< Frame direction: transmitted.
< Frame direction: received.
< Frame direction: received.
< Frame direction: received.
< Frame direction: received.
< Frame direction: received.
< Frame direction: received.
< Frame direction: received.
Definition at line 123 of file test_bit_analysis.c.
References BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), CAN_DIR_RX, CAN_DIR_TX, check(), make_msg(), and n.
Referenced by main().
validate_candidate_dbc()
static void validate_candidate_dbc (const ba_candidate_t * candidate) static
< Maximum payload of a CAN FD frame.
Definition at line 206 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, CANFD_DATA_MAX, check(), dbc_create_empty(), dbc_decode_physical(), dbc_extract_raw(), dbc_find_message(), dbc_free(), dbc_load_file(), dbc_save_file(), dbc_upsert_message(), dbc_upsert_signal(), n, put_u64_le(), sig, and plot_signal_t::unit.
Referenced by candidate_tests().
validate_candidate_dbc_roundtrip()
static void validate_candidate_dbc_roundtrip (const ba_candidate_t * candidate, uint32_t message_id, int is_extended, uint8_t dlc, const uint64_t * raw_values, size_t raw_count) static
< Maximum payload of a CAN FD frame.
Definition at line 289 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_sign_extend(), CANFD_DATA_MAX, check(), dbc_create_empty(), dbc_decode_physical(), dbc_extract_raw(), dbc_find_message(), dbc_free(), dbc_load_file(), dbc_save_file(), dbc_upsert_message(), dbc_upsert_signal(), n, put_candidate_raw(), sig, and plot_signal_t::unit.
Referenced by motorola_candidate_tests().
candidate_tests()
static void candidate_tests (void) static
< Frame direction: received.
Definition at line 374 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_extract_unsigned(), BA_INPUT_CONTINUOUS, BA_SEGMENT_STEP, ba_session_add_segment(), ba_session_analyze(), ba_session_capture_baseline(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_end_segment(), ba_session_init(), ba_session_load_json(), ba_session_push_frame(), ba_session_save_json(), ba_session_set_input(), CAN_DIR_RX, check(), n, put_u64_le(), and validate_candidate_dbc().
Referenced by main().
baseline_segment_tests()
static void baseline_segment_tests (void) static
< Frame direction: received.
< Frame direction: received.
Definition at line 501 of file test_bit_analysis.c.
References BA_INPUT_BOOLEAN, BA_SEGMENT_BASELINE, BA_SEGMENT_STEP, ba_session_add_segment(), ba_session_analyze(), ba_session_capture_baseline(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_end_segment(), ba_session_init(), ba_session_push_frame(), ba_session_set_input(), CAN_DIR_RX, check(), n, and put_u64_le().
Referenced by main().
validation_segment_tests()
static void validation_segment_tests (void) static
< Frame direction: received.
< Frame direction: received.
Definition at line 560 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_candidate_validate_segments(), BA_INPUT_CONTINUOUS, BA_SEGMENT_STEP, BA_SEGMENT_VALIDATION, ba_session_add_segment(), ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_end_segment(), ba_session_init(), ba_session_load_json(), ba_session_push_frame(), ba_session_save_json(), ba_session_set_input(), CAN_DIR_RX, check(), n, ba_candidate_t::offset, and put_u64_le().
Referenced by main().
transition_match_tests()
static void transition_match_tests (void) static
< Frame direction: received.
Definition at line 703 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, BA_INPUT_BOOLEAN, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_load_json(), ba_session_push_frame(), ba_session_save_json(), ba_session_set_input(), CAN_DIR_RX, check(), n, and put_u64_le().
Referenced by main().
checksum_tests()
static void checksum_tests (void) static
< Frame direction: received.
Definition at line 796 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), CAN_DIR_RX, check(), and n.
Referenced by main().
mux_tests()
static void mux_tests (void) static
< Frame direction: received.
Definition at line 846 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_load_json(), ba_session_push_frame(), ba_session_save_json(), CAN_DIR_RX, check(), ba_candidate_t::mux_score, n, and put_u64_le().
Referenced by main().
timestamp_tests()
static void timestamp_tests (void) static
< Frame direction: received.
Definition at line 968 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_load_json(), ba_session_push_frame(), ba_session_save_json(), CAN_DIR_RX, check(), n, and put_u64_le().
Referenced by main().
signed_candidate_tests()
static void signed_candidate_tests (void) static
< Frame direction: received.
Definition at line 1064 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, BA_INPUT_CONTINUOUS, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), ba_session_set_input(), CAN_DIR_RX, check(), n, put_u64_le(), and ba_candidate_t::total_score.
Referenced by main().
motorola_candidate_tests()
static void motorola_candidate_tests (void) static
< Frame direction: received.
Definition at line 1122 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, BA_BYTE_ORDER_MOTOROLA, BA_INPUT_CONTINUOUS, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), ba_session_set_input(), CAN_DIR_RX, check(), n, put_motorola(), ba_candidate_t::total_score, and validate_candidate_dbc_roundtrip().
Referenced by main().
lag_tests()
static void lag_tests (void) static
< Frame direction: received.
Definition at line 1197 of file test_bit_analysis.c.
References BA_BYTE_ORDER_INTEL, BA_INPUT_CONTINUOUS, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), ba_session_set_input(), CAN_DIR_RX, check(), n, and put_u64_le().
Referenced by main().
bit_lag_tests()
static void bit_lag_tests (void) static
< Frame direction: received.
Definition at line 1252 of file test_bit_analysis.c.
References BA_INPUT_BOOLEAN, ba_session_analyze(), BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), ba_session_set_input(), CAN_DIR_RX, check(), n, and put_u64_le().
Referenced by main().
elapsed_seconds()
static double elapsed_seconds (const struct timespec * a, const struct timespec * b) static
Definition at line 1292 of file test_bit_analysis.c.
References n.
Referenced by fast_path_tests().
fast_path_tests()
static void fast_path_tests (void) static
< Frame direction: received.
Definition at line 1299 of file test_bit_analysis.c.
References BA_SESSION_CAPTURING, ba_session_configure_target(), ba_session_destroy(), ba_session_init(), ba_session_push_frame(), CAN_DIR_RX, check(), elapsed_seconds(), n, and put_u64_le().
Referenced by main().
main()
int main (void)
Definition at line 1331 of file test_bit_analysis.c.
References baseline_segment_tests(), bit_lag_tests(), candidate_tests(), checksum_tests(), extraction_tests(), failures, fast_path_tests(), lag_tests(), motorola_candidate_tests(), mux_tests(), n, signed_candidate_tests(), target_filter_tests(), timestamp_tests(), transition_match_tests(), and validation_segment_tests().
Variable Documentation
failures
int failures static
Definition at line 24 of file test_bit_analysis.c.
Referenced by check(), and main().